export default () => ({
  instanceConfig: {
    context: {
      theme: 'senseish',
    },
  },
  genericObjects: [
    {
      getLayout() {
        return {
          qInfo: {
            qId: '7dfabd0f-17ce-47b8-9914-e25b6a6fb949',
            qType: 'embeddedsnapshot',
          },
          qMeta: {
            privileges: ['read', 'update', 'delete', 'publish'],
            title: '',
            description: '',
            annotation: '',
          },
          qBookmark: {
            qStateData: [
              {
                qStateName: '$',
                qFieldItems: [],
              },
              {
                qStateName: 'state 2',
                qFieldItems: [],
              },
            ],
            qUtcModifyTime: 44469.35068287037,
            qVariableItems: [],
            qPatches: [],
          },
          qFieldInfos: [],
          creationDate: '2021-09-30T08:24:59.788Z',
          qSelectionInfo: {},
          qHyperCube: {
            qSize: {
              qcx: 1,
              qcy: 30,
            },
            qDimensionInfo: [
              {
                qFallbackTitle: 'Regional Sales Mgr',
                qApprMaxGlyphCount: 15,
                qCardinal: 15,
                qSortIndicator: 'A',
                qGroupFallbackTitles: ['Regional Sales Mgr'],
                qGroupPos: 0,
                qStateCounts: {
                  qLocked: 0,
                  qSelected: 0,
                  qOption: 15,
                  qDeselected: 0,
                  qAlternative: 0,
                  qExcluded: 0,
                  qSelectedExcluded: 0,
                  qLockedExcluded: 0,
                },
                qTags: ['$ascii', '$text'],
                qDimensionType: 'D',
                qGrouping: 'N',
                qNumFormat: {
                  qType: 'U',
                  qnDec: 0,
                  qUseThou: 0,
                },
                qIsAutoFormat: true,
                qGroupFieldDefs: ['Regional Sales Mgr Name'],
                qMin: 'NaN',
                qMax: 'NaN',
                qAttrExprInfo: [],
                qAttrDimInfo: [],
                qCardinalities: {
                  qCardinal: 15,
                  qHypercubeCardinal: 15,
                  qAllValuesCardinal: -1,
                },
                qLibraryId: '5b68675d-30a0-4e5c-9c11-efe9dba2fd1a',
                title: 'Regional Sales Mgr',
                autoSort: true,
                cId: 'gvctUe',
                othersLabel: 'Others',
              },
              {
                qFallbackTitle: 'Year',
                qApprMaxGlyphCount: 4,
                qCardinal: 2,
                qSortIndicator: 'A',
                qGroupFallbackTitles: ['Year'],
                qGroupPos: 0,
                qStateCounts: {
                  qLocked: 0,
                  qSelected: 0,
                  qOption: 2,
                  qDeselected: 0,
                  qAlternative: 0,
                  qExcluded: 0,
                  qSelectedExcluded: 0,
                  qLockedExcluded: 0,
                },
                qTags: ['$numeric', '$integer'],
                qDimensionType: 'N',
                qGrouping: 'N',
                qNumFormat: {
                  qType: 'I',
                  qnDec: 0,
                  qUseThou: 0,
                  qFmt: '###0',
                  qDec: '.',
                  qThou: ',',
                },
                qIsAutoFormat: true,
                qGroupFieldDefs: ['Year'],
                qMin: 2006,
                qMax: 2007,
                qContinuousAxes: true,
                qAttrExprInfo: [],
                qAttrDimInfo: [],
                qCardinalities: {
                  qCardinal: 2,
                  qHypercubeCardinal: 2,
                  qAllValuesCardinal: -1,
                },
                qLibraryId: '700c622d-693d-46dd-b538-426edd0175c2',
                title: 'Year',
                autoSort: true,
                cId: 'mmTjy',
                othersLabel: 'Others',
              },
            ],
            qMeasureInfo: [
              {
                qFallbackTitle: 'Actual Amount',
                qApprMaxGlyphCount: 11,
                qCardinal: 0,
                qSortIndicator: 'D',
                qNumFormat: {
                  qType: 'U',
                  qnDec: 0,
                  qUseThou: 0,
                },
                qMin: 1062.96,
                qMax: 18761530.729999986,
                qIsAutoFormat: true,
                qAttrExprInfo: [],
                qAttrDimInfo: [],
                qLibraryId: 'uQbd',
                qTrendLines: [],
                autoSort: true,
                cId: 'ctvcxd',
                numFormatFromTemplate: true,
                quarantine: {
                  qNumFormat: {},
                  isCustomFormatted: false,
                },
              },
            ],
            qEffectiveInterColumnSortOrder: [1, 0],
            qGrandTotalRow: [],
            qDataPages: [],
            qPivotDataPages: [],
            qStackedDataPages: [],
            qMode: 'K',
            qNoOfLeftDims: 2,
            qTreeNodesOnDim: [],
            qColumnOrder: [],
          },
          refLine: {
            refLines: [],
          },
          showTitles: true,
          title: '',
          subtitle: '',
          footnote: '',
          disableNavMenu: false,
          showDetails: false,
          showDisclaimer: true,
          orientation: 'horizontal',
          presentation: {
            visibleComponents: 'points_box',
          },
          gridlines: {
            auto: true,
            spacing: 2,
          },
          dataPoint: {
            bubbleScales: 40,
            displacement: 'jitter',
          },
          color: {
            point: {
              auto: false,
              mode: 'byExpression',
              useBaseColors: 'off',
              paletteColor: {
                index: 6,
              },
              useDimColVal: true,
              persistent: true,
              expressionIsColor: true,
              measureScheme: 'sg',
              reverseScheme: false,
              dimensionScheme: '12',
              autoMinMax: true,
              measureMin: 0,
              measureMax: 10,
              expression: 4284776576,
            },
            formatting: {
              numFormatFromTemplate: true,
            },
            expressionLabel: '',
            box: {
              paletteColor: {
                color: '#e6e6e6',
                index: -1,
              },
            },
          },
          legend: {
            show: true,
            dock: 'auto',
            showTitle: true,
          },
          measureAxis: {
            show: 'all',
            dock: 'near',
            spacing: 1,
            autoMinMax: true,
            minMax: 'min',
            min: 0,
            max: 10,
          },
          dimensionAxis: {
            show: 'all',
            label: 'auto',
            dock: 'near',
          },
          visualization: 'distributionplot',
          version: '0.25.6',
          sorting: {
            autoSort: true,
          },
          qUndoExclude: {
            hashCode: 1242703102,
            qHyperCube: {
              qSize: {
                qcx: 1,
                qcy: 30,
              },
              qDimensionInfo: [
                {
                  qFallbackTitle: 'Regional Sales Mgr',
                  qApprMaxGlyphCount: 15,
                  qCardinal: 15,
                  qSortIndicator: 'A',
                  qGroupFallbackTitles: ['Regional Sales Mgr'],
                  qGroupPos: 0,
                  qStateCounts: {
                    qLocked: 0,
                    qSelected: 0,
                    qOption: 15,
                    qDeselected: 0,
                    qAlternative: 0,
                    qExcluded: 0,
                    qSelectedExcluded: 0,
                    qLockedExcluded: 0,
                  },
                  qTags: ['$ascii', '$text'],
                  qDimensionType: 'D',
                  qGrouping: 'N',
                  qNumFormat: {
                    qType: 'U',
                    qnDec: 0,
                    qUseThou: 0,
                  },
                  qIsAutoFormat: true,
                  qGroupFieldDefs: ['Regional Sales Mgr Name'],
                  qMin: 'NaN',
                  qMax: 'NaN',
                  qAttrExprInfo: [],
                  qAttrDimInfo: [],
                  qCardinalities: {
                    qCardinal: 15,
                    qHypercubeCardinal: 15,
                    qAllValuesCardinal: -1,
                  },
                  qLibraryId: '5b68675d-30a0-4e5c-9c11-efe9dba2fd1a',
                  title: 'Regional Sales Mgr',
                  autoSort: true,
                  cId: 'gvctUe',
                  othersLabel: 'Others',
                },
                {
                  qFallbackTitle: 'Year',
                  qApprMaxGlyphCount: 4,
                  qCardinal: 2,
                  qSortIndicator: 'A',
                  qGroupFallbackTitles: ['Year'],
                  qGroupPos: 0,
                  qStateCounts: {
                    qLocked: 0,
                    qSelected: 0,
                    qOption: 2,
                    qDeselected: 0,
                    qAlternative: 0,
                    qExcluded: 0,
                    qSelectedExcluded: 0,
                    qLockedExcluded: 0,
                  },
                  qTags: ['$numeric', '$integer'],
                  qDimensionType: 'N',
                  qGrouping: 'N',
                  qNumFormat: {
                    qType: 'I',
                    qnDec: 0,
                    qUseThou: 0,
                    qFmt: '###0',
                    qDec: '.',
                    qThou: ',',
                  },
                  qIsAutoFormat: true,
                  qGroupFieldDefs: ['Year'],
                  qMin: 2006,
                  qMax: 2007,
                  qContinuousAxes: true,
                  qAttrExprInfo: [
                    {
                      qMin: 1062.96,
                      qMax: 1062.96,
                      qFallbackTitle:
                        'Min( total <[Year]> Aggr( Sum ([Actual Amount]), [Year], [Regional Sales Mgr Name] ), 0 )',
                      qMinText: '1062.96',
                      qMaxText: '1062.96',
                      qNumFormat: {
                        qType: 'U',
                        qnDec: 0,
                        qUseThou: 0,
                      },
                      qIsAutoFormat: true,
                      id: 'minBoxValue',
                    },
                    {
                      qMin: 18761530.729999986,
                      qMax: 18761530.729999986,
                      qFallbackTitle:
                        'Max( total <[Year]> Aggr( Sum ([Actual Amount]), [Year], [Regional Sales Mgr Name] ), 1 )',
                      qMinText: '18761530.73',
                      qMaxText: '18761530.73',
                      qNumFormat: {
                        qType: 'U',
                        qnDec: 0,
                        qUseThou: 0,
                      },
                      qIsAutoFormat: true,
                      id: 'maxBoxValue',
                    },
                  ],
                  qAttrDimInfo: [],
                  qCardinalities: {
                    qCardinal: 2,
                    qHypercubeCardinal: 2,
                    qAllValuesCardinal: -1,
                  },
                  qLibraryId: '700c622d-693d-46dd-b538-426edd0175c2',
                  title: 'Year',
                  autoSort: true,
                  cId: 'mmTjy',
                  othersLabel: 'Others',
                },
              ],
              qMeasureInfo: [
                {
                  qFallbackTitle: 'Actual Amount',
                  qApprMaxGlyphCount: 11,
                  qCardinal: 0,
                  qSortIndicator: 'D',
                  qNumFormat: {
                    qType: 'U',
                    qnDec: 0,
                    qUseThou: 0,
                  },
                  qMin: 1062.96,
                  qMax: 18761530.729999986,
                  qIsAutoFormat: true,
                  qAttrExprInfo: [
                    {
                      qMin: 4278255360,
                      qMax: 4294967040,
                      qFallbackTitle:
                        "If([Regional Sales Mgr Name] = 'Asia', rgb(255,0,0),\r\n\tIf([Regional Sales Mgr Name]='South America', rgb(255,255,0),\n\t\tIf([Regional Sales Mgr Name]='Scott Porter', rgb(0,255,0), rgb(100,128,128))))",
                      qMinText: 'RGB(0,255,0)',
                      qMaxText: 'RGB(255,255,0)',
                      qNumFormat: {
                        qType: 'U',
                        qnDec: 0,
                        qUseThou: 0,
                      },
                      qIsAutoFormat: true,
                      id: 'colorByExpression',
                    },
                  ],
                  qAttrDimInfo: [],
                  qLibraryId: 'uQbd',
                  qTrendLines: [],
                  autoSort: true,
                  cId: 'ctvcxd',
                  numFormatFromTemplate: true,
                  quarantine: {
                    qNumFormat: {},
                    isCustomFormatted: false,
                  },
                },
              ],
              qEffectiveInterColumnSortOrder: [1, 0],
              qGrandTotalRow: [],
              qDataPages: [],
              qPivotDataPages: [],
              qStackedDataPages: [
                {
                  qData: [
                    {
                      qElemNo: 0,
                      qValue: 0,
                      qType: 'R',
                      qMaxPos: 92187533.67999998,
                      qMinNeg: 0,
                      qUp: 0,
                      qDown: 0,
                      qRow: 0,
                      qSubNodes: [
                        {
                          qText: '2006',
                          qElemNo: 1,
                          qValue: 2006,
                          qType: 'N',
                          qMaxPos: 45830159.25999999,
                          qMinNeg: 0,
                          qUp: 0,
                          qDown: 0,
                          qRow: 0,
                          qSubNodes: [
                            {
                              qText: 'Africa',
                              qElemNo: 10,
                              qValue: 'NaN',
                              qType: 'N',
                              qMaxPos: 98916.31,
                              qMinNeg: 0,
                              qUp: 0,
                              qDown: 0,
                              qRow: 0,
                              qSubNodes: [
                                {
                                  qText: '98916.31',
                                  qElemNo: 0,
                                  qValue: 98916.31,
                                  qType: 'V',
                                  qMaxPos: 0,
                                  qMinNeg: 0,
                                  qUp: 0,
                                  qDown: 0,
                                  qRow: 0,
                                  qSubNodes: [],
                                  qAttrExps: {
                                    qValues: [
                                      {
                                        qText: 'RGB(100,128,128)',
                                        qNum: 4284776576,
                                      },
                                    ],
                                  },
                                },
                              ],
                            },
                            {
                              qText: 'Asia',
                              qElemNo: 0,
                              qValue: 'NaN',
                              qType: 'N',
                              qMaxPos: 845371.2099999997,
                              qMinNeg: 0,
                              qUp: 0,
                              qDown: 0,
                              qRow: 1,
                              qSubNodes: [
                                {
                                  qText: '845371.21',
                                  qElemNo: 0,
                                  qValue: 845371.2099999997,
                                  qType: 'V',
                                  qMaxPos: 0,
                                  qMinNeg: 0,
                                  qUp: 0,
                                  qDown: 0,
                                  qRow: 1,
                                  qSubNodes: [],
                                  qAttrExps: {
                                    qValues: [
                                      {
                                        qText: 'RGB(255,0,0)',
                                        qNum: 4294901760,
                                      },
                                    ],
                                  },
                                },
                              ],
                            },
                            {
                              qText: 'Brian Sleicher',
                              qElemNo: 14,
                              qValue: 'NaN',
                              qType: 'N',
                              qMaxPos: 438765.45999999996,
                              qMinNeg: 0,
                              qUp: 0,
                              qDown: 0,
                              qRow: 2,
                              qSubNodes: [
                                {
                                  qText: '438765.46',
                                  qElemNo: 0,
                                  qValue: 438765.45999999996,
                                  qType: 'V',
                                  qMaxPos: 0,
                                  qMinNeg: 0,
                                  qUp: 0,
                                  qDown: 0,
                                  qRow: 2,
                                  qSubNodes: [],
                                  qAttrExps: {
                                    qValues: [
                                      {
                                        qText: 'RGB(100,128,128)',
                                        qNum: 4284776576,
                                      },
                                    ],
                                  },
                                },
                              ],
                            },
                            {
                              qText: 'Central America',
                              qElemNo: 9,
                              qValue: 'NaN',
                              qType: 'N',
                              qMaxPos: 3276.1399999999994,
                              qMinNeg: 0,
                              qUp: 0,
                              qDown: 0,
                              qRow: 3,
                              qSubNodes: [
                                {
                                  qText: '3276.14',
                                  qElemNo: 0,
                                  qValue: 3276.1399999999994,
                                  qType: 'V',
                                  qMaxPos: 0,
                                  qMinNeg: 0,
                                  qUp: 0,
                                  qDown: 0,
                                  qRow: 3,
                                  qSubNodes: [],
                                  qAttrExps: {
                                    qValues: [
                                      {
                                        qText: 'RGB(100,128,128)',
                                        qNum: 4284776576,
                                      },
                                    ],
                                  },
                                },
                              ],
                            },
                            {
                              qText: 'Eastern Europe',
                              qElemNo: 7,
                              qValue: 'NaN',
                              qType: 'N',
                              qMaxPos: 9989.699999999999,
                              qMinNeg: 0,
                              qUp: 0,
                              qDown: 0,
                              qRow: 4,
                              qSubNodes: [
                                {
                                  qText: '9989.7',
                                  qElemNo: 0,
                                  qValue: 9989.699999999999,
                                  qType: 'V',
                                  qMaxPos: 0,
                                  qMinNeg: 0,
                                  qUp: 0,
                                  qDown: 0,
                                  qRow: 4,
                                  qSubNodes: [],
                                  qAttrExps: {
                                    qValues: [
                                      {
                                        qText: 'RGB(100,128,128)',
                                        qNum: 4284776576,
                                      },
                                    ],
                                  },
                                },
                              ],
                            },
                            {
                              qText: 'Gage Hartman',
                              qElemNo: 11,
                              qValue: 'NaN',
                              qType: 'N',
                              qMaxPos: 1543453.9400000002,
                              qMinNeg: 0,
                              qUp: 0,
                              qDown: 0,
                              qRow: 5,
                              qSubNodes: [
                                {
                                  qText: '1543453.94',
                                  qElemNo: 0,
                                  qValue: 1543453.9400000002,
                                  qType: 'V',
                                  qMaxPos: 0,
                                  qMinNeg: 0,
                                  qUp: 0,
                                  qDown: 0,
                                  qRow: 5,
                                  qSubNodes: [],
                                  qAttrExps: {
                                    qValues: [
                                      {
                                        qText: 'RGB(100,128,128)',
                                        qNum: 4284776576,
                                      },
                                    ],
                                  },
                                },
                              ],
                            },
                            {
                              qText: 'Greg Ballantyne',
                              qElemNo: 13,
                              qValue: 'NaN',
                              qType: 'N',
                              qMaxPos: 3909402.230000002,
                              qMinNeg: 0,
                              qUp: 0,
                              qDown: 0,
                              qRow: 6,
                              qSubNodes: [
                                {
                                  qText: '3909402.23',
                                  qElemNo: 0,
                                  qValue: 3909402.230000002,
                                  qType: 'V',
                                  qMaxPos: 0,
                                  qMinNeg: 0,
                                  qUp: 0,
                                  qDown: 0,
                                  qRow: 6,
                                  qSubNodes: [],
                                  qAttrExps: {
                                    qValues: [
                                      {
                                        qText: 'RGB(100,128,128)',
                                        qNum: 4284776576,
                                      },
                                    ],
                                  },
                                },
                              ],
                            },
                            {
                              qText: 'Greg Kaphammer',
                              qElemNo: 4,
                              qValue: 'NaN',
                              qType: 'N',
                              qMaxPos: 12125359.960000003,
                              qMinNeg: 0,
                              qUp: 0,
                              qDown: 0,
                              qRow: 7,
                              qSubNodes: [
                                {
                                  qText: '12125359.96',
                                  qElemNo: 0,
                                  qValue: 12125359.960000003,
                                  qType: 'V',
                                  qMaxPos: 0,
                                  qMinNeg: 0,
                                  qUp: 0,
                                  qDown: 0,
                                  qRow: 7,
                                  qSubNodes: [],
                                  qAttrExps: {
                                    qValues: [
                                      {
                                        qText: 'RGB(100,128,128)',
                                        qNum: 4284776576,
                                      },
                                    ],
                                  },
                                },
                              ],
                            },
                            {
                              qText: 'Harold Ogden',
                              qElemNo: 3,
                              qValue: 'NaN',
                              qType: 'N',
                              qMaxPos: 2568409.1799999997,
                              qMinNeg: 0,
                              qUp: 0,
                              qDown: 0,
                              qRow: 8,
                              qSubNodes: [
                                {
                                  qText: '2568409.18',
                                  qElemNo: 0,
                                  qValue: 2568409.1799999997,
                                  qType: 'V',
                                  qMaxPos: 0,
                                  qMinNeg: 0,
                                  qUp: 0,
                                  qDown: 0,
                                  qRow: 8,
                                  qSubNodes: [],
                                  qAttrExps: {
                                    qValues: [
                                      {
                                        qText: 'RGB(100,128,128)',
                                        qNum: 4284776576,
                                      },
                                    ],
                                  },
                                },
                              ],
                            },
                            {
                              qText: 'House Accounts',
                              qElemNo: 5,
                              qValue: 'NaN',
                              qType: 'N',
                              qMaxPos: 1466527.6000000006,
                              qMinNeg: 0,
                              qUp: 0,
                              qDown: 0,
                              qRow: 9,
                              qSubNodes: [
                                {
                                  qText: '1466527.6',
                                  qElemNo: 0,
                                  qValue: 1466527.6000000006,
                                  qType: 'V',
                                  qMaxPos: 0,
                                  qMinNeg: 0,
                                  qUp: 0,
                                  qDown: 0,
                                  qRow: 9,
                                  qSubNodes: [],
                                  qAttrExps: {
                                    qValues: [
                                      {
                                        qText: 'RGB(100,128,128)',
                                        qNum: 4284776576,
                                      },
                                    ],
                                  },
                                },
                              ],
                            },
                            {
                              qText: 'Japan',
                              qElemNo: 1,
                              qValue: 'NaN',
                              qType: 'N',
                              qMaxPos: 38120.56999999999,
                              qMinNeg: 0,
                              qUp: 0,
                              qDown: 0,
                              qRow: 10,
                              qSubNodes: [
                                {
                                  qText: '38120.57',
                                  qElemNo: 0,
                                  qValue: 38120.56999999999,
                                  qType: 'V',
                                  qMaxPos: 0,
                                  qMinNeg: 0,
                                  qUp: 0,
                                  qDown: 0,
                                  qRow: 10,
                                  qSubNodes: [],
                                  qAttrExps: {
                                    qValues: [
                                      {
                                        qText: 'RGB(100,128,128)',
                                        qNum: 4284776576,
                                      },
                                    ],
                                  },
                                },
                              ],
                            },
                            {
                              qText: 'Scott Porter',
                              qElemNo: 12,
                              qValue: 'NaN',
                              qType: 'N',
                              qMaxPos: 2181520.7799999993,
                              qMinNeg: 0,
                              qUp: 0,
                              qDown: 0,
                              qRow: 11,
                              qSubNodes: [
                                {
                                  qText: '2181520.78',
                                  qElemNo: 0,
                                  qValue: 2181520.7799999993,
                                  qType: 'V',
                                  qMaxPos: 0,
                                  qMinNeg: 0,
                                  qUp: 0,
                                  qDown: 0,
                                  qRow: 11,
                                  qSubNodes: [],
                                  qAttrExps: {
                                    qValues: [
                                      {
                                        qText: 'RGB(0,255,0)',
                                        qNum: 4278255360,
                                      },
                                    ],
                                  },
                                },
                              ],
                            },
                            {
                              qText: 'South America',
                              qElemNo: 8,
                              qValue: 'NaN',
                              qType: 'N',
                              qMaxPos: 18761530.729999986,
                              qMinNeg: 0,
                              qUp: 0,
                              qDown: 0,
                              qRow: 12,
                              qSubNodes: [
                                {
                                  qText: '18761530.73',
                                  qElemNo: 0,
                                  qValue: 18761530.729999986,
                                  qType: 'V',
                                  qMaxPos: 0,
                                  qMinNeg: 0,
                                  qUp: 0,
                                  qDown: 0,
                                  qRow: 12,
                                  qSubNodes: [],
                                  qAttrExps: {
                                    qValues: [
                                      {
                                        qText: 'RGB(255,255,0)',
                                        qNum: 4294967040,
                                      },
                                    ],
                                  },
                                },
                              ],
                            },
                            {
                              qText: 'Wes Stockton',
                              qElemNo: 2,
                              qValue: 'NaN',
                              qType: 'N',
                              qMaxPos: 1062.96,
                              qMinNeg: 0,
                              qUp: 0,
                              qDown: 0,
                              qRow: 13,
                              qSubNodes: [
                                {
                                  qText: '1062.96',
                                  qElemNo: 0,
                                  qValue: 1062.96,
                                  qType: 'V',
                                  qMaxPos: 0,
                                  qMinNeg: 0,
                                  qUp: 0,
                                  qDown: 0,
                                  qRow: 13,
                                  qSubNodes: [],
                                  qAttrExps: {
                                    qValues: [
                                      {
                                        qText: 'RGB(100,128,128)',
                                        qNum: 4284776576,
                                      },
                                    ],
                                  },
                                },
                              ],
                            },
                            {
                              qText: 'Western Europe',
                              qElemNo: 6,
                              qValue: 'NaN',
                              qType: 'N',
                              qMaxPos: 1838452.4899999998,
                              qMinNeg: 0,
                              qUp: 0,
                              qDown: 0,
                              qRow: 14,
                              qSubNodes: [
                                {
                                  qText: '1838452.49',
                                  qElemNo: 0,
                                  qValue: 1838452.4899999998,
                                  qType: 'V',
                                  qMaxPos: 0,
                                  qMinNeg: 0,
                                  qUp: 0,
                                  qDown: 0,
                                  qRow: 14,
                                  qSubNodes: [],
                                  qAttrExps: {
                                    qValues: [
                                      {
                                        qText: 'RGB(100,128,128)',
                                        qNum: 4284776576,
                                      },
                                    ],
                                  },
                                },
                              ],
                            },
                          ],
                          qAttrExps: {
                            qValues: [
                              {
                                qText: '1062.96',
                                qNum: 1062.96,
                              },
                              {
                                qText: '18761530.73',
                                qNum: 18761530.729999986,
                              },
                            ],
                          },
                        },
                        {
                          qText: '2007',
                          qElemNo: 0,
                          qValue: 2007,
                          qType: 'N',
                          qMaxPos: 46357374.41999999,
                          qMinNeg: 0,
                          qUp: 0,
                          qDown: 0,
                          qRow: 15,
                          qSubNodes: [
                            {
                              qText: 'Africa',
                              qElemNo: 10,
                              qValue: 'NaN',
                              qType: 'N',
                              qMaxPos: 98916.31,
                              qMinNeg: 0,
                              qUp: 0,
                              qDown: 0,
                              qRow: 15,
                              qSubNodes: [
                                {
                                  qText: '98916.31',
                                  qElemNo: 0,
                                  qValue: 98916.31,
                                  qType: 'V',
                                  qMaxPos: 0,
                                  qMinNeg: 0,
                                  qUp: 0,
                                  qDown: 0,
                                  qRow: 15,
                                  qSubNodes: [],
                                  qAttrExps: {
                                    qValues: [
                                      {
                                        qText: 'RGB(100,128,128)',
                                        qNum: 4284776576,
                                      },
                                    ],
                                  },
                                },
                              ],
                            },
                            {
                              qText: 'Asia',
                              qElemNo: 0,
                              qValue: 'NaN',
                              qType: 'N',
                              qMaxPos: 845371.2099999997,
                              qMinNeg: 0,
                              qUp: 0,
                              qDown: 0,
                              qRow: 16,
                              qSubNodes: [
                                {
                                  qText: '845371.21',
                                  qElemNo: 0,
                                  qValue: 845371.2099999997,
                                  qType: 'V',
                                  qMaxPos: 0,
                                  qMinNeg: 0,
                                  qUp: 0,
                                  qDown: 0,
                                  qRow: 16,
                                  qSubNodes: [],
                                  qAttrExps: {
                                    qValues: [
                                      {
                                        qText: 'RGB(255,0,0)',
                                        qNum: 4294901760,
                                      },
                                    ],
                                  },
                                },
                              ],
                            },
                            {
                              qText: 'Brian Sleicher',
                              qElemNo: 14,
                              qValue: 'NaN',
                              qType: 'N',
                              qMaxPos: 438765.45999999996,
                              qMinNeg: 0,
                              qUp: 0,
                              qDown: 0,
                              qRow: 17,
                              qSubNodes: [
                                {
                                  qText: '438765.46',
                                  qElemNo: 0,
                                  qValue: 438765.45999999996,
                                  qType: 'V',
                                  qMaxPos: 0,
                                  qMinNeg: 0,
                                  qUp: 0,
                                  qDown: 0,
                                  qRow: 17,
                                  qSubNodes: [],
                                  qAttrExps: {
                                    qValues: [
                                      {
                                        qText: 'RGB(100,128,128)',
                                        qNum: 4284776576,
                                      },
                                    ],
                                  },
                                },
                              ],
                            },
                            {
                              qText: 'Central America',
                              qElemNo: 9,
                              qValue: 'NaN',
                              qType: 'N',
                              qMaxPos: 3276.1399999999994,
                              qMinNeg: 0,
                              qUp: 0,
                              qDown: 0,
                              qRow: 18,
                              qSubNodes: [
                                {
                                  qText: '3276.14',
                                  qElemNo: 0,
                                  qValue: 3276.1399999999994,
                                  qType: 'V',
                                  qMaxPos: 0,
                                  qMinNeg: 0,
                                  qUp: 0,
                                  qDown: 0,
                                  qRow: 18,
                                  qSubNodes: [],
                                  qAttrExps: {
                                    qValues: [
                                      {
                                        qText: 'RGB(100,128,128)',
                                        qNum: 4284776576,
                                      },
                                    ],
                                  },
                                },
                              ],
                            },
                            {
                              qText: 'Eastern Europe',
                              qElemNo: 7,
                              qValue: 'NaN',
                              qType: 'N',
                              qMaxPos: 9989.699999999999,
                              qMinNeg: 0,
                              qUp: 0,
                              qDown: 0,
                              qRow: 19,
                              qSubNodes: [
                                {
                                  qText: '9989.7',
                                  qElemNo: 0,
                                  qValue: 9989.699999999999,
                                  qType: 'V',
                                  qMaxPos: 0,
                                  qMinNeg: 0,
                                  qUp: 0,
                                  qDown: 0,
                                  qRow: 19,
                                  qSubNodes: [],
                                  qAttrExps: {
                                    qValues: [
                                      {
                                        qText: 'RGB(100,128,128)',
                                        qNum: 4284776576,
                                      },
                                    ],
                                  },
                                },
                              ],
                            },
                            {
                              qText: 'Gage Hartman',
                              qElemNo: 11,
                              qValue: 'NaN',
                              qType: 'N',
                              qMaxPos: 1543453.9400000002,
                              qMinNeg: 0,
                              qUp: 0,
                              qDown: 0,
                              qRow: 20,
                              qSubNodes: [
                                {
                                  qText: '1543453.94',
                                  qElemNo: 0,
                                  qValue: 1543453.9400000002,
                                  qType: 'V',
                                  qMaxPos: 0,
                                  qMinNeg: 0,
                                  qUp: 0,
                                  qDown: 0,
                                  qRow: 20,
                                  qSubNodes: [],
                                  qAttrExps: {
                                    qValues: [
                                      {
                                        qText: 'RGB(100,128,128)',
                                        qNum: 4284776576,
                                      },
                                    ],
                                  },
                                },
                              ],
                            },
                            {
                              qText: 'Greg Ballantyne',
                              qElemNo: 13,
                              qValue: 'NaN',
                              qType: 'N',
                              qMaxPos: 3909402.230000002,
                              qMinNeg: 0,
                              qUp: 0,
                              qDown: 0,
                              qRow: 21,
                              qSubNodes: [
                                {
                                  qText: '3909402.23',
                                  qElemNo: 0,
                                  qValue: 3909402.230000002,
                                  qType: 'V',
                                  qMaxPos: 0,
                                  qMinNeg: 0,
                                  qUp: 0,
                                  qDown: 0,
                                  qRow: 21,
                                  qSubNodes: [],
                                  qAttrExps: {
                                    qValues: [
                                      {
                                        qText: 'RGB(100,128,128)',
                                        qNum: 4284776576,
                                      },
                                    ],
                                  },
                                },
                              ],
                            },
                            {
                              qText: 'Greg Kaphammer',
                              qElemNo: 4,
                              qValue: 'NaN',
                              qType: 'N',
                              qMaxPos: 12125359.960000003,
                              qMinNeg: 0,
                              qUp: 0,
                              qDown: 0,
                              qRow: 22,
                              qSubNodes: [
                                {
                                  qText: '12125359.96',
                                  qElemNo: 0,
                                  qValue: 12125359.960000003,
                                  qType: 'V',
                                  qMaxPos: 0,
                                  qMinNeg: 0,
                                  qUp: 0,
                                  qDown: 0,
                                  qRow: 22,
                                  qSubNodes: [],
                                  qAttrExps: {
                                    qValues: [
                                      {
                                        qText: 'RGB(100,128,128)',
                                        qNum: 4284776576,
                                      },
                                    ],
                                  },
                                },
                              ],
                            },
                            {
                              qText: 'Harold Ogden',
                              qElemNo: 3,
                              qValue: 'NaN',
                              qType: 'N',
                              qMaxPos: 2568409.1799999997,
                              qMinNeg: 0,
                              qUp: 0,
                              qDown: 0,
                              qRow: 23,
                              qSubNodes: [
                                {
                                  qText: '2568409.18',
                                  qElemNo: 0,
                                  qValue: 2568409.1799999997,
                                  qType: 'V',
                                  qMaxPos: 0,
                                  qMinNeg: 0,
                                  qUp: 0,
                                  qDown: 0,
                                  qRow: 23,
                                  qSubNodes: [],
                                  qAttrExps: {
                                    qValues: [
                                      {
                                        qText: 'RGB(100,128,128)',
                                        qNum: 4284776576,
                                      },
                                    ],
                                  },
                                },
                              ],
                            },
                            {
                              qText: 'House Accounts',
                              qElemNo: 5,
                              qValue: 'NaN',
                              qType: 'N',
                              qMaxPos: 1993742.7600000005,
                              qMinNeg: 0,
                              qUp: 0,
                              qDown: 0,
                              qRow: 24,
                              qSubNodes: [
                                {
                                  qText: '1993742.76',
                                  qElemNo: 0,
                                  qValue: 1993742.7600000005,
                                  qType: 'V',
                                  qMaxPos: 0,
                                  qMinNeg: 0,
                                  qUp: 0,
                                  qDown: 0,
                                  qRow: 24,
                                  qSubNodes: [],
                                  qAttrExps: {
                                    qValues: [
                                      {
                                        qText: 'RGB(100,128,128)',
                                        qNum: 4284776576,
                                      },
                                    ],
                                  },
                                },
                              ],
                            },
                            {
                              qText: 'Japan',
                              qElemNo: 1,
                              qValue: 'NaN',
                              qType: 'N',
                              qMaxPos: 38120.56999999999,
                              qMinNeg: 0,
                              qUp: 0,
                              qDown: 0,
                              qRow: 25,
                              qSubNodes: [
                                {
                                  qText: '38120.57',
                                  qElemNo: 0,
                                  qValue: 38120.56999999999,
                                  qType: 'V',
                                  qMaxPos: 0,
                                  qMinNeg: 0,
                                  qUp: 0,
                                  qDown: 0,
                                  qRow: 25,
                                  qSubNodes: [],
                                  qAttrExps: {
                                    qValues: [
                                      {
                                        qText: 'RGB(100,128,128)',
                                        qNum: 4284776576,
                                      },
                                    ],
                                  },
                                },
                              ],
                            },
                            {
                              qText: 'Scott Porter',
                              qElemNo: 12,
                              qValue: 'NaN',
                              qType: 'N',
                              qMaxPos: 2181520.7799999993,
                              qMinNeg: 0,
                              qUp: 0,
                              qDown: 0,
                              qRow: 26,
                              qSubNodes: [
                                {
                                  qText: '2181520.78',
                                  qElemNo: 0,
                                  qValue: 2181520.7799999993,
                                  qType: 'V',
                                  qMaxPos: 0,
                                  qMinNeg: 0,
                                  qUp: 0,
                                  qDown: 0,
                                  qRow: 26,
                                  qSubNodes: [],
                                  qAttrExps: {
                                    qValues: [
                                      {
                                        qText: 'RGB(0,255,0)',
                                        qNum: 4278255360,
                                      },
                                    ],
                                  },
                                },
                              ],
                            },
                            {
                              qText: 'South America',
                              qElemNo: 8,
                              qValue: 'NaN',
                              qType: 'N',
                              qMaxPos: 18761530.729999986,
                              qMinNeg: 0,
                              qUp: 0,
                              qDown: 0,
                              qRow: 27,
                              qSubNodes: [
                                {
                                  qText: '18761530.73',
                                  qElemNo: 0,
                                  qValue: 18761530.729999986,
                                  qType: 'V',
                                  qMaxPos: 0,
                                  qMinNeg: 0,
                                  qUp: 0,
                                  qDown: 0,
                                  qRow: 27,
                                  qSubNodes: [],
                                  qAttrExps: {
                                    qValues: [
                                      {
                                        qText: 'RGB(255,255,0)',
                                        qNum: 4294967040,
                                      },
                                    ],
                                  },
                                },
                              ],
                            },
                            {
                              qText: 'Wes Stockton',
                              qElemNo: 2,
                              qValue: 'NaN',
                              qType: 'N',
                              qMaxPos: 1062.96,
                              qMinNeg: 0,
                              qUp: 0,
                              qDown: 0,
                              qRow: 28,
                              qSubNodes: [
                                {
                                  qText: '1062.96',
                                  qElemNo: 0,
                                  qValue: 1062.96,
                                  qType: 'V',
                                  qMaxPos: 0,
                                  qMinNeg: 0,
                                  qUp: 0,
                                  qDown: 0,
                                  qRow: 28,
                                  qSubNodes: [],
                                  qAttrExps: {
                                    qValues: [
                                      {
                                        qText: 'RGB(100,128,128)',
                                        qNum: 4284776576,
                                      },
                                    ],
                                  },
                                },
                              ],
                            },
                            {
                              qText: 'Western Europe',
                              qElemNo: 6,
                              qValue: 'NaN',
                              qType: 'N',
                              qMaxPos: 1838452.4899999998,
                              qMinNeg: 0,
                              qUp: 0,
                              qDown: 0,
                              qRow: 29,
                              qSubNodes: [
                                {
                                  qText: '1838452.49',
                                  qElemNo: 0,
                                  qValue: 1838452.4899999998,
                                  qType: 'V',
                                  qMaxPos: 0,
                                  qMinNeg: 0,
                                  qUp: 0,
                                  qDown: 0,
                                  qRow: 29,
                                  qSubNodes: [],
                                  qAttrExps: {
                                    qValues: [
                                      {
                                        qText: 'RGB(100,128,128)',
                                        qNum: 4284776576,
                                      },
                                    ],
                                  },
                                },
                              ],
                            },
                          ],
                          qAttrExps: {
                            qValues: [
                              {
                                qText: '1062.96',
                                qNum: 1062.96,
                              },
                              {
                                qText: '18761530.73',
                                qNum: 18761530.729999986,
                              },
                            ],
                          },
                        },
                      ],
                    },
                  ],
                  qArea: {
                    qLeft: 0,
                    qTop: 0,
                    qWidth: 1,
                    qHeight: 2,
                  },
                },
              ],
              qMode: 'K',
              qNoOfLeftDims: 2,
              qTreeNodesOnDim: [],
              qColumnOrder: [],
            },
          },
          snapshotData: {
            object: {
              size: {
                w: 945,
                h: 391,
              },
            },
            rtl: false,
            content: {
              chartData: {},
              size: {},
            },
            parent: {
              h: 857,
              w: 1920,
            },
          },
          visualizationType: 'distributionplot',
          sourceObjectId: 'tAAJH',
          sheetId: 'df55769b-64d9-4694-b717-30b63331b5fc',
          timestamp: 1632990299781,
          isClone: false,
          supportExport: true,
        };
      },
      getEffectiveProperties: {},
    },
  ],
});
