export default () => ({
  instanceConfig: {
    context: {
      theme: 'senseish',
    },
  },
  genericObjects: [
    {
      getLayout() {
        return {
          qInfo: {
            qId: '1143088f-8f82-401f-b49f-89460336969e',
            qType: 'embeddedsnapshot',
          },
          qMeta: {
            privileges: ['read', 'update', 'delete', 'publish'],
            title: '',
            description: '',
            annotation: '',
          },
          qBookmark: {
            qStateData: [
              {
                qStateName: '$',
                qFieldItems: [],
              },
              {
                qStateName: 'state 2',
                qFieldItems: [],
              },
            ],
            qUtcModifyTime: 44468.50324074074,
            qVariableItems: [],
            qPatches: [],
          },
          qFieldInfos: [],
          creationDate: '2021-09-29T12:04:40.517Z',
          qSelectionInfo: {},
          boxplotDef: {
            qHyperCube: {
              qSize: {
                qcx: 2,
                qcy: 12,
              },
              qDimensionInfo: [
                {
                  qFallbackTitle: 'Month',
                  qApprMaxGlyphCount: 3,
                  qCardinal: 12,
                  qSortIndicator: 'A',
                  qGroupFallbackTitles: ['Month'],
                  qGroupPos: 0,
                  qStateCounts: {
                    qLocked: 0,
                    qSelected: 0,
                    qOption: 12,
                    qDeselected: 0,
                    qAlternative: 0,
                    qExcluded: 0,
                    qSelectedExcluded: 0,
                    qLockedExcluded: 0,
                  },
                  qTags: ['$numeric', '$integer'],
                  qDimensionType: 'N',
                  qGrouping: 'N',
                  qNumFormat: {
                    qType: 'U',
                    qnDec: 0,
                    qUseThou: 0,
                  },
                  qIsAutoFormat: true,
                  qGroupFieldDefs: ['Month'],
                  qMin: 1,
                  qMax: 12,
                  qContinuousAxes: true,
                  qAttrExprInfo: [],
                  qAttrDimInfo: [],
                  qCardinalities: {
                    qCardinal: 12,
                    qHypercubeCardinal: 12,
                    qAllValuesCardinal: -1,
                  },
                  qLibraryId: '50a5fd45-6023-487a-a6d1-f71681f0dafe',
                  title: 'Month',
                  autoSort: true,
                  cId: 'zhUPHf',
                  othersLabel: 'Others',
                },
              ],
              qMeasureInfo: [
                {
                  qFallbackTitle: 'Actual Amount',
                  qApprMaxGlyphCount: 11,
                  qCardinal: 0,
                  qSortIndicator: 'D',
                  qNumFormat: {
                    qType: 'U',
                    qnDec: 0,
                    qUseThou: 0,
                  },
                  qMin: 44884486.24000001,
                  qMax: 45959669.79999998,
                  qIsAutoFormat: true,
                  qAttrExprInfo: [],
                  qAttrDimInfo: [],
                  qLibraryId: 'uQbd',
                  qTrendLines: [],
                  autoSort: true,
                  cId: 'zNPr',
                  numFormatFromTemplate: true,
                  quarantine: {
                    qNumFormat: {},
                    isCustomFormatted: false,
                  },
                },
              ],
              qEffectiveInterColumnSortOrder: [1, 0],
              qGrandTotalRow: [
                {
                  qText: '46258458.11',
                  qNum: 46258458.110000014,
                  qElemNumber: -1,
                  qState: 'X',
                  qIsTotalCell: true,
                },
              ],
              qDataPages: [],
              qPivotDataPages: [],
              qStackedDataPages: [],
              qMode: 'S',
              qNoOfLeftDims: -1,
              qTreeNodesOnDim: [],
              qColumnOrder: [],
            },
            calculations: {
              auto: true,
              mode: 'fractiles',
              parameters: {
                tukey: 2,
                fractiles: 0.1,
                stdDev: 3,
              },
            },
            elements: {
              firstWhisker: {
                name: '',
                expression: null,
              },
              boxStart: {
                name: '',
                expression: null,
              },
              boxMiddle: {
                name: '',
                expression: null,
              },
              boxEnd: {
                name: '',
                expression: null,
              },
              lastWhisker: {
                name: '',
                expression: null,
              },
              outliers: {
                include: true,
                sortOutliers: false,
              },
            },
            presentation: {
              whiskers: {
                show: false,
              },
            },
            color: {
              auto: false,
              mode: 'primary',
              box: {
                paletteColor: {
                  color: '#05e612',
                  index: -1,
                },
              },
              point: {
                paletteColor: {
                  color: '#276e27',
                  index: 3,
                },
              },
              expressionIsColor: true,
              useBaseColors: 'off',
              expressionLabel: '',
            },
            sorting: {
              autoSort: true,
            },
          },
          refLine: {
            refLines: [
              {
                show: true,
                label: 'Ref',
                showLabel: true,
                refLineExpr: {
                  value: 45000000,
                  label: '45000000',
                },
                showValue: true,
                paletteColor: {
                  index: -1,
                  color: '#269011',
                },
                style: {
                  lineThickness: 2,
                  lineType: '8 4',
                },
                coloredBackground: false,
                cId: 'PpkbC',
              },
            ],
          },
          showTitles: true,
          title: '',
          subtitle: '',
          footnote: '',
          disableNavMenu: false,
          showDetails: false,
          showDisclaimer: true,
          orientation: 'vertical',
          gridlines: {
            auto: false,
            spacing: 0,
          },
          measureAxis: {
            show: 'none',
            dock: 'near',
            spacing: 0.5,
            autoMinMax: true,
            minMax: 'min',
            min: 0,
            max: 10,
          },
          dimensionAxis: {
            show: 'all',
            label: 'auto',
            dock: 'near',
          },
          visualization: 'boxplot',
          version: '0.26.2',
          sorting: {
            autoSort: true,
            elementId: 'firstWhisker',
            sortCriteria: {
              sortByAscii: 0,
              sortByExpression: 0,
              sortByNumeric: 0,
            },
          },
          qUndoExclude: {
            hashCode: -680220581,
            box: {
              qHyperCube: {
                qSize: {
                  qcx: 5,
                  qcy: 1,
                },
                qDimensionInfo: [],
                qMeasureInfo: [
                  {
                    qFallbackTitle: 'First whisker',
                    qApprMaxGlyphCount: 11,
                    qCardinal: 0,
                    qSortIndicator: 'N',
                    qNumFormat: {
                      qType: 'U',
                      qnDec: 0,
                      qUseThou: 0,
                    },
                    qMin: 44941823.21999999,
                    qMax: 44941823.21999999,
                    qIsAutoFormat: true,
                    qAttrExprInfo: [
                      {
                        qMin: 'NaN',
                        qMax: 'NaN',
                        qFallbackTitle: "='10th percentile'",
                        qNumFormat: {
                          qType: 'U',
                          qnDec: 0,
                          qUseThou: 0,
                        },
                        qIsAutoFormat: true,
                        id: 'tooltip',
                      },
                    ],
                    qAttrDimInfo: [],
                    qTrendLines: [],
                    cId: 'bfPpbKp',
                  },
                  {
                    qFallbackTitle: 'Box start',
                    qApprMaxGlyphCount: 10,
                    qCardinal: 0,
                    qSortIndicator: 'N',
                    qNumFormat: {
                      qType: 'U',
                      qnDec: 0,
                      qUseThou: 0,
                    },
                    qMin: 45060894.60000001,
                    qMax: 45060894.60000001,
                    qIsAutoFormat: true,
                    qAttrExprInfo: [
                      {
                        qMin: 'NaN',
                        qMax: 'NaN',
                        qFallbackTitle: "='First quartile'",
                        qNumFormat: {
                          qType: 'U',
                          qnDec: 0,
                          qUseThou: 0,
                        },
                        qIsAutoFormat: true,
                        id: 'tooltip',
                      },
                    ],
                    qAttrDimInfo: [],
                    qTrendLines: [],
                    cId: 'kBTQmQp',
                  },
                  {
                    qFallbackTitle: 'Center line',
                    qApprMaxGlyphCount: 11,
                    qCardinal: 0,
                    qSortIndicator: 'N',
                    qNumFormat: {
                      qType: 'U',
                      qnDec: 0,
                      qUseThou: 0,
                    },
                    qMin: 45125846.19000001,
                    qMax: 45125846.19000001,
                    qIsAutoFormat: true,
                    qAttrExprInfo: [
                      {
                        qMin: 'NaN',
                        qMax: 'NaN',
                        qFallbackTitle: "='Median'",
                        qNumFormat: {
                          qType: 'U',
                          qnDec: 0,
                          qUseThou: 0,
                        },
                        qIsAutoFormat: true,
                        id: 'tooltip',
                      },
                    ],
                    qAttrDimInfo: [],
                    qTrendLines: [],
                    cId: 'vZLAppw',
                  },
                  {
                    qFallbackTitle: 'Box end',
                    qApprMaxGlyphCount: 13,
                    qCardinal: 0,
                    qSortIndicator: 'N',
                    qNumFormat: {
                      qType: 'U',
                      qnDec: 0,
                      qUseThou: 0,
                    },
                    qMin: 45286156.5475,
                    qMax: 45286156.5475,
                    qIsAutoFormat: true,
                    qAttrExprInfo: [
                      {
                        qMin: 'NaN',
                        qMax: 'NaN',
                        qFallbackTitle: "='Third quartile'",
                        qNumFormat: {
                          qType: 'U',
                          qnDec: 0,
                          qUseThou: 0,
                        },
                        qIsAutoFormat: true,
                        id: 'tooltip',
                      },
                    ],
                    qAttrDimInfo: [],
                    qTrendLines: [],
                    cId: 'ZYdC',
                  },
                  {
                    qFallbackTitle: 'Last whisker',
                    qApprMaxGlyphCount: 12,
                    qCardinal: 0,
                    qSortIndicator: 'N',
                    qNumFormat: {
                      qType: 'U',
                      qnDec: 0,
                      qUseThou: 0,
                    },
                    qMin: 45885185.818,
                    qMax: 45885185.818,
                    qIsAutoFormat: true,
                    qAttrExprInfo: [
                      {
                        qMin: 'NaN',
                        qMax: 'NaN',
                        qFallbackTitle: "='90th percentile'",
                        qNumFormat: {
                          qType: 'U',
                          qnDec: 0,
                          qUseThou: 0,
                        },
                        qIsAutoFormat: true,
                        id: 'tooltip',
                      },
                    ],
                    qAttrDimInfo: [],
                    qTrendLines: [],
                    cId: 'kCULXA',
                  },
                ],
                qEffectiveInterColumnSortOrder: [0, 1, 2, 3, 4],
                qGrandTotalRow: [
                  {
                    qText: '44941823.22',
                    qNum: 44941823.21999999,
                    qElemNumber: -1,
                    qState: 'X',
                    qIsTotalCell: true,
                  },
                  {
                    qText: '45060894.6',
                    qNum: 45060894.60000001,
                    qElemNumber: -1,
                    qState: 'X',
                    qIsTotalCell: true,
                  },
                  {
                    qText: '45125846.19',
                    qNum: 45125846.19000001,
                    qElemNumber: -1,
                    qState: 'X',
                    qIsTotalCell: true,
                  },
                  {
                    qText: '45286156.5475',
                    qNum: 45286156.5475,
                    qElemNumber: -1,
                    qState: 'X',
                    qIsTotalCell: true,
                  },
                  {
                    qText: '45885185.818',
                    qNum: 45885185.818,
                    qElemNumber: -1,
                    qState: 'X',
                    qIsTotalCell: true,
                  },
                ],
                qDataPages: [
                  {
                    qMatrix: [
                      [
                        {
                          qText: '44941823.22',
                          qNum: 44941823.21999999,
                          qElemNumber: 0,
                          qState: 'L',
                          qAttrExps: {
                            qValues: [
                              {
                                qText: '10th percentile',
                                qNum: 'NaN',
                              },
                            ],
                          },
                          qInExtRow: true,
                        },
                        {
                          qText: '45060894.6',
                          qNum: 45060894.60000001,
                          qElemNumber: 0,
                          qState: 'L',
                          qAttrExps: {
                            qValues: [
                              {
                                qText: 'First quartile',
                                qNum: 'NaN',
                              },
                            ],
                          },
                          qInExtRow: true,
                        },
                        {
                          qText: '45125846.19',
                          qNum: 45125846.19000001,
                          qElemNumber: 0,
                          qState: 'L',
                          qAttrExps: {
                            qValues: [
                              {
                                qText: 'Median',
                                qNum: 'NaN',
                              },
                            ],
                          },
                          qInExtRow: true,
                        },
                        {
                          qText: '45286156.5475',
                          qNum: 45286156.5475,
                          qElemNumber: 0,
                          qState: 'L',
                          qAttrExps: {
                            qValues: [
                              {
                                qText: 'Third quartile',
                                qNum: 'NaN',
                              },
                            ],
                          },
                          qInExtRow: true,
                        },
                        {
                          qText: '45885185.818',
                          qNum: 45885185.818,
                          qElemNumber: 0,
                          qState: 'L',
                          qAttrExps: {
                            qValues: [
                              {
                                qText: '90th percentile',
                                qNum: 'NaN',
                              },
                            ],
                          },
                          qInExtRow: true,
                        },
                      ],
                    ],
                    qTails: [],
                    qArea: {
                      qLeft: 0,
                      qTop: 0,
                      qWidth: 5,
                      qHeight: 1,
                    },
                  },
                ],
                qPivotDataPages: [],
                qStackedDataPages: [],
                qMode: 'S',
                qNoOfLeftDims: -1,
                qTreeNodesOnDim: [],
                qColumnOrder: [],
              },
            },
            outliers: {
              qHyperCube: {
                qSize: {
                  qcx: 1,
                  qcy: 4,
                },
                qDimensionInfo: [
                  {
                    qFallbackTitle:
                      '=aggr( If( Sum ([Actual Amount]) < Fractile( total  Aggr( Sum ([Actual Amount]),  [Month] ) ,0.1 ) or Sum ([Actual Amount]) > Fractile( total  Aggr( Sum ([Actual Amount]),  [Month] ) ,0.9 ),  [Month] ), [Month] )',
                    qApprMaxGlyphCount: 3,
                    qCardinal: 4,
                    qSortIndicator: 'A',
                    qGroupFallbackTitles: [
                      '=aggr( If( Sum ([Actual Amount]) < Fractile( total  Aggr( Sum ([Actual Amount]),  [Month] ) ,0.1 ) or Sum ([Actual Amount]) > Fractile( total  Aggr( Sum ([Actual Amount]),  [Month] ) ,0.9 ),  [Month] ), [Month] )',
                    ],
                    qGroupPos: 0,
                    qStateCounts: {
                      qLocked: 0,
                      qSelected: 0,
                      qOption: 4,
                      qDeselected: 0,
                      qAlternative: 0,
                      qExcluded: 0,
                      qSelectedExcluded: 0,
                      qLockedExcluded: 0,
                    },
                    qTags: ['$numeric', '$integer'],
                    qDimensionType: 'N',
                    qGrouping: 'N',
                    qNumFormat: {
                      qType: 'U',
                      qnDec: 0,
                      qUseThou: 0,
                    },
                    qIsAutoFormat: true,
                    qGroupFieldDefs: [
                      '=aggr( If( Sum ([Actual Amount]) < Fractile( total  Aggr( Sum ([Actual Amount]),  [Month] ) ,0.1 ) or Sum ([Actual Amount]) > Fractile( total  Aggr( Sum ([Actual Amount]),  [Month] ) ,0.9 ),  [Month] ), [Month] )',
                    ],
                    qMin: 7,
                    qMax: 12,
                    qAttrExprInfo: [],
                    qAttrDimInfo: [],
                    qIsCalculated: true,
                    qCardinalities: {
                      qCardinal: 4,
                      qHypercubeCardinal: 4,
                      qAllValuesCardinal: -1,
                    },
                    autoSort: true,
                    cId: 'zMgJX',
                    othersLabel: 'Others',
                  },
                  {
                    qFallbackTitle: 'Month',
                    qApprMaxGlyphCount: 3,
                    qCardinal: 12,
                    qSortIndicator: 'A',
                    qGroupFallbackTitles: ['Month'],
                    qGroupPos: 0,
                    qStateCounts: {
                      qLocked: 0,
                      qSelected: 0,
                      qOption: 12,
                      qDeselected: 0,
                      qAlternative: 0,
                      qExcluded: 0,
                      qSelectedExcluded: 0,
                      qLockedExcluded: 0,
                    },
                    qTags: ['$numeric', '$integer'],
                    qDimensionType: 'N',
                    qGrouping: 'N',
                    qNumFormat: {
                      qType: 'U',
                      qnDec: 0,
                      qUseThou: 0,
                    },
                    qIsAutoFormat: true,
                    qGroupFieldDefs: ['Month'],
                    qMin: 7,
                    qMax: 12,
                    qContinuousAxes: true,
                    qAttrExprInfo: [],
                    qAttrDimInfo: [],
                    qCardinalities: {
                      qCardinal: 12,
                      qHypercubeCardinal: 4,
                      qAllValuesCardinal: -1,
                    },
                    qLibraryId: '50a5fd45-6023-487a-a6d1-f71681f0dafe',
                    title: 'Month',
                    autoSort: true,
                    cId: 'zhUPHf',
                    othersLabel: 'Others',
                  },
                ],
                qMeasureInfo: [
                  {
                    qFallbackTitle:
                      '=aggr( If( Sum ([Actual Amount]) < Fractile( total  Aggr( Sum ([Actual Amount]),  [Month] ) ,0.1 ) or Sum ([Actual Amount]) > Fractile( total  Aggr( Sum ([Actual Amount]),  [Month] ) ,0.9 ), Sum ([Actual Amount]) ), [Month] )',
                    qApprMaxGlyphCount: 11,
                    qCardinal: 0,
                    qSortIndicator: 'D',
                    qNumFormat: {
                      qType: 'U',
                      qnDec: 0,
                      qUseThou: 0,
                    },
                    qMin: 44884486.24000001,
                    qMax: 45959669.79999998,
                    qIsAutoFormat: true,
                    qAttrExprInfo: [],
                    qAttrDimInfo: [],
                    qTrendLines: [],
                    autoSort: true,
                    cId: 'zNPr',
                    numFormatFromTemplate: true,
                    quarantine: {
                      qNumFormat: {},
                      isCustomFormatted: false,
                    },
                  },
                ],
                qEffectiveInterColumnSortOrder: [0, 1],
                qGrandTotalRow: [],
                qDataPages: [],
                qPivotDataPages: [],
                qStackedDataPages: [
                  {
                    qData: [
                      {
                        qElemNo: 0,
                        qValue: 0,
                        qType: 'R',
                        qMaxPos: 181722084.88,
                        qMinNeg: 0,
                        qUp: 0,
                        qDown: 0,
                        qRow: 0,
                        qSubNodes: [
                          {
                            qText: 'Jul',
                            qElemNo: 3,
                            qValue: 7,
                            qType: 'N',
                            qMaxPos: 44933258.99999999,
                            qMinNeg: 0,
                            qUp: 0,
                            qDown: 0,
                            qRow: 0,
                            qSubNodes: [
                              {
                                qText: 'Jul',
                                qElemNo: 8,
                                qValue: 7,
                                qType: 'N',
                                qMaxPos: 44933258.99999999,
                                qMinNeg: 0,
                                qUp: 0,
                                qDown: 0,
                                qRow: 0,
                                qSubNodes: [
                                  {
                                    qText: '44933259',
                                    qElemNo: 0,
                                    qValue: 44933258.99999999,
                                    qType: 'V',
                                    qMaxPos: 0,
                                    qMinNeg: 0,
                                    qUp: 0,
                                    qDown: 0,
                                    qRow: 0,
                                    qSubNodes: [],
                                  },
                                ],
                              },
                            ],
                          },
                          {
                            qText: 'Sep',
                            qElemNo: 0,
                            qValue: 9,
                            qType: 'N',
                            qMaxPos: 45959669.79999998,
                            qMinNeg: 0,
                            qUp: 0,
                            qDown: 0,
                            qRow: 1,
                            qSubNodes: [
                              {
                                qText: 'Sep',
                                qElemNo: 3,
                                qValue: 9,
                                qType: 'N',
                                qMaxPos: 45959669.79999998,
                                qMinNeg: 0,
                                qUp: 0,
                                qDown: 0,
                                qRow: 1,
                                qSubNodes: [
                                  {
                                    qText: '45959669.8',
                                    qElemNo: 0,
                                    qValue: 45959669.79999998,
                                    qType: 'V',
                                    qMaxPos: 0,
                                    qMinNeg: 0,
                                    qUp: 0,
                                    qDown: 0,
                                    qRow: 1,
                                    qSubNodes: [],
                                  },
                                ],
                              },
                            ],
                          },
                          {
                            qText: 'Nov',
                            qElemNo: 1,
                            qValue: 11,
                            qType: 'N',
                            qMaxPos: 45944669.839999996,
                            qMinNeg: 0,
                            qUp: 0,
                            qDown: 0,
                            qRow: 2,
                            qSubNodes: [
                              {
                                qText: 'Nov',
                                qElemNo: 4,
                                qValue: 11,
                                qType: 'N',
                                qMaxPos: 45944669.839999996,
                                qMinNeg: 0,
                                qUp: 0,
                                qDown: 0,
                                qRow: 2,
                                qSubNodes: [
                                  {
                                    qText: '45944669.84',
                                    qElemNo: 0,
                                    qValue: 45944669.839999996,
                                    qType: 'V',
                                    qMaxPos: 0,
                                    qMinNeg: 0,
                                    qUp: 0,
                                    qDown: 0,
                                    qRow: 2,
                                    qSubNodes: [],
                                  },
                                ],
                              },
                            ],
                          },
                          {
                            qText: 'Dec',
                            qElemNo: 2,
                            qValue: 12,
                            qType: 'N',
                            qMaxPos: 44884486.24000001,
                            qMinNeg: 0,
                            qUp: 0,
                            qDown: 0,
                            qRow: 3,
                            qSubNodes: [
                              {
                                qText: 'Dec',
                                qElemNo: 7,
                                qValue: 12,
                                qType: 'N',
                                qMaxPos: 44884486.24000001,
                                qMinNeg: 0,
                                qUp: 0,
                                qDown: 0,
                                qRow: 3,
                                qSubNodes: [
                                  {
                                    qText: '44884486.24',
                                    qElemNo: 0,
                                    qValue: 44884486.24000001,
                                    qType: 'V',
                                    qMaxPos: 0,
                                    qMinNeg: 0,
                                    qUp: 0,
                                    qDown: 0,
                                    qRow: 3,
                                    qSubNodes: [],
                                  },
                                ],
                              },
                            ],
                          },
                        ],
                      },
                    ],
                    qArea: {
                      qLeft: 0,
                      qTop: 0,
                      qWidth: 1,
                      qHeight: 4,
                    },
                  },
                ],
                qMode: 'K',
                qNoOfLeftDims: 2,
                qTreeNodesOnDim: [],
                qColumnOrder: [],
              },
            },
          },
          snapshotData: {
            object: {
              size: {
                w: 945,
                h: 391,
              },
            },
            rtl: false,
            content: {
              chartData: {},
              size: {},
            },
            parent: {
              h: 857,
              w: 1920,
            },
          },
          visualizationType: 'boxplot',
          sourceObjectId: 'pPTkJMG',
          sheetId: 'bb52098c-5bf6-44f3-b475-c3c817e77f19',
          timestamp: 1632917080503,
          isClone: false,
          supportExport: true,
        };
      },
      getEffectiveProperties: {},
    },
  ],
});
