export default () => ({
  instanceConfig: {
    context: {
      theme: 'theme-global',
    },
  },
  genericObjects: [
    {
      getLayout() {
        return {
          qInfo: {
            qId: '54e99f36-9df5-41bc-8cf5-3bc26f94da37',
            qType: 'embeddedsnapshot',
          },
          qMeta: {
            privileges: ['read', 'update', 'delete', 'exportdata'],
          },
          qBookmark: {
            qStateData: [
              {
                qStateName: '$',
                qFieldItems: [],
              },
            ],
            qUtcModifyTime: 44413.424259259256,
            qVariableItems: [],
            qPatches: [],
          },
          qFieldInfos: [],
          creationDate: '2021-08-05T08:10:56.881Z',
          qSelectionInfo: {},
          boxplotDef: {
            qHyperCube: {
              qSize: {
                qcx: 3,
                qcy: 18,
              },
              qDimensionInfo: [
                {
                  qFallbackTitle: 'Dim2',
                  qApprMaxGlyphCount: 1,
                  qCardinal: 6,
                  qSortIndicator: 'A',
                  qGroupFallbackTitles: ['Dim2'],
                  qGroupPos: 0,
                  qStateCounts: {
                    qLocked: 0,
                    qSelected: 0,
                    qOption: 6,
                    qDeselected: 0,
                    qAlternative: 0,
                    qExcluded: 0,
                    qSelectedExcluded: 0,
                    qLockedExcluded: 0,
                  },
                  qTags: ['$ascii', '$text'],
                  qDimensionType: 'D',
                  qGrouping: 'N',
                  qNumFormat: {
                    qType: 'U',
                    qnDec: 0,
                    qUseThou: 0,
                  },
                  qIsAutoFormat: true,
                  qGroupFieldDefs: ['Dim2'],
                  qMin: 'NaN',
                  qMax: 'NaN',
                  qAttrExprInfo: [],
                  qAttrDimInfo: [],
                  qCardinalities: {
                    qCardinal: 6,
                    qHypercubeCardinal: 6,
                    qAllValuesCardinal: -1,
                  },
                  autoSort: true,
                  cId: 'eCbjdH',
                  othersLabel: 'Others',
                },
                {
                  qFallbackTitle: 'Dim3',
                  qApprMaxGlyphCount: 1,
                  qCardinal: 3,
                  qSortIndicator: 'A',
                  qGroupFallbackTitles: ['Dim3'],
                  qGroupPos: 0,
                  qStateCounts: {
                    qLocked: 0,
                    qSelected: 0,
                    qOption: 3,
                    qDeselected: 0,
                    qAlternative: 0,
                    qExcluded: 0,
                    qSelectedExcluded: 0,
                    qLockedExcluded: 0,
                  },
                  qTags: ['$ascii', '$text'],
                  qDimensionType: 'D',
                  qGrouping: 'N',
                  qNumFormat: {
                    qType: 'U',
                    qnDec: 0,
                    qUseThou: 0,
                  },
                  qIsAutoFormat: true,
                  qGroupFieldDefs: ['Dim3'],
                  qMin: 'NaN',
                  qMax: 'NaN',
                  qAttrExprInfo: [],
                  qAttrDimInfo: [],
                  qCardinalities: {
                    qCardinal: 3,
                    qHypercubeCardinal: 3,
                    qAllValuesCardinal: -1,
                  },
                  autoSort: true,
                  cId: 'Yjthu',
                  othersLabel: 'Others',
                },
              ],
              qMeasureInfo: [
                {
                  qFallbackTitle: 'Avg(Expression2)*10000',
                  qApprMaxGlyphCount: 15,
                  qCardinal: 0,
                  qSortIndicator: 'D',
                  qNumFormat: {
                    qType: 'R',
                    qnDec: 0,
                    qUseThou: 0,
                    qFmt: '##############',
                    qDec: ',',
                    qThou: ' ',
                  },
                  qMin: 854.7008547008547,
                  qMax: 22804.878048780487,
                  qIsAutoFormat: true,
                  qAttrExprInfo: [],
                  qAttrDimInfo: [],
                  qTrendLines: [],
                  autoSort: true,
                  cId: 'PQEMC',
                  numFormatFromTemplate: true,
                },
              ],
              qEffectiveInterColumnSortOrder: [0, 1, 2],
              qGrandTotalRow: [
                {
                  qText: '11282,910483485',
                  qNum: 11282.91048348492,
                  qElemNumber: -1,
                  qState: 'X',
                  qIsTotalCell: true,
                },
              ],
              qDataPages: [],
              qPivotDataPages: [],
              qStackedDataPages: [],
              qMode: 'S',
              qNoOfLeftDims: -1,
              qTreeNodesOnDim: [],
              qColumnOrder: [],
            },
            calculations: {
              auto: true,
              mode: 'fractiles',
              parameters: {
                tukey: 1.5,
                fractiles: 0.05,
                stdDev: 3,
              },
            },
            elements: {
              firstWhisker: {
                name: '',
                expression: null,
              },
              boxStart: {
                name: '',
                expression: null,
              },
              boxMiddle: {
                name: '',
                expression: null,
              },
              boxEnd: {
                name: '',
                expression: null,
              },
              lastWhisker: {
                name: '',
                expression: null,
              },
              outliers: {
                include: true,
                sortOutliers: true,
              },
            },
            presentation: {
              whiskers: {
                show: true,
              },
            },
            color: {
              auto: false,
              mode: 'byExpression',
              box: {
                paletteColor: {
                  index: -1,
                  color: '#e6e6e6',
                },
              },
              point: {
                paletteColor: {
                  index: 6,
                  color: '#4477aa',
                },
              },
              expressionIsColor: true,
              expression: 'NaN',
            },
            sorting: {
              autoSort: false,
              sortCriteria: {
                sortByAscii: 1,
                sortByNumeric: 1,
                sortByLoadOrder: 1,
                sortByExpression: 1,
              },
              expression: 0.1591319882,
            },
          },
          refLine: {
            refLines: [],
          },
          showTitles: true,
          title: '',
          subtitle: '',
          footnote: '',
          disableNavMenu: false,
          showDetails: false,
          showDisclaimer: true,
          orientation: 'vertical',
          gridlines: {
            auto: true,
            spacing: 2,
          },
          measureAxis: {
            show: 'all',
            dock: 'near',
            spacing: 1,
            autoMinMax: true,
            minMax: 'min',
            min: 0,
            max: 10,
          },
          dimensionAxis: {
            show: 'all',
            label: 'auto',
            dock: 'near',
          },
          visualization: 'boxplot',
          qUndoExclude: {
            hashCode: -141200522,
            box: {
              qHyperCube: {
                qSize: {
                  qcx: 6,
                  qcy: 3,
                },
                qDimensionInfo: [
                  {
                    qFallbackTitle: 'Dim3',
                    qApprMaxGlyphCount: 1,
                    qCardinal: 3,
                    qSortIndicator: 'A',
                    qGroupFallbackTitles: ['Dim3'],
                    qGroupPos: 0,
                    qStateCounts: {
                      qLocked: 0,
                      qSelected: 0,
                      qOption: 3,
                      qDeselected: 0,
                      qAlternative: 0,
                      qExcluded: 0,
                      qSelectedExcluded: 0,
                      qLockedExcluded: 0,
                    },
                    qTags: ['$ascii', '$text'],
                    qDimensionType: 'D',
                    qGrouping: 'N',
                    qNumFormat: {
                      qType: 'U',
                      qnDec: 0,
                      qUseThou: 0,
                    },
                    qIsAutoFormat: true,
                    qGroupFieldDefs: ['Dim3'],
                    qMin: 'NaN',
                    qMax: 'NaN',
                    qAttrExprInfo: [],
                    qAttrDimInfo: [],
                    qCardinalities: {
                      qCardinal: 3,
                      qHypercubeCardinal: 3,
                      qAllValuesCardinal: -1,
                    },
                    autoSort: true,
                    cId: 'Yjthu',
                    othersLabel: 'Others',
                  },
                ],
                qMeasureInfo: [
                  {
                    qFallbackTitle: 'First whisker',
                    qApprMaxGlyphCount: 15,
                    qCardinal: 0,
                    qSortIndicator: 'N',
                    qNumFormat: {
                      qType: 'U',
                      qnDec: 0,
                      qUseThou: 0,
                    },
                    qMin: 1901.025641025641,
                    qMax: 2596.1306653809065,
                    qIsAutoFormat: true,
                    qAttrExprInfo: [
                      {
                        qMin: 'NaN',
                        qMax: 'NaN',
                        qFallbackTitle: "='green'",
                        qNumFormat: {
                          qType: 'U',
                          qnDec: 0,
                          qUseThou: 0,
                        },
                        qIsAutoFormat: true,
                        id: 'colorByExpression',
                      },
                      {
                        qMin: 'NaN',
                        qMax: 'NaN',
                        qFallbackTitle: "='5th percentile'",
                        qNumFormat: {
                          qType: 'U',
                          qnDec: 0,
                          qUseThou: 0,
                        },
                        qIsAutoFormat: true,
                        id: 'tooltip',
                      },
                    ],
                    qAttrDimInfo: [],
                    qTrendLines: [],
                    cId: 'PRmfkb',
                  },
                  {
                    qFallbackTitle: 'Box start',
                    qApprMaxGlyphCount: 15,
                    qCardinal: 0,
                    qSortIndicator: 'N',
                    qNumFormat: {
                      qType: 'U',
                      qnDec: 0,
                      qUseThou: 0,
                    },
                    qMin: 6115,
                    qMax: 6503.214285714285,
                    qIsAutoFormat: true,
                    qAttrExprInfo: [
                      {
                        qMin: 'NaN',
                        qMax: 'NaN',
                        qFallbackTitle: "='First quartile'",
                        qNumFormat: {
                          qType: 'U',
                          qnDec: 0,
                          qUseThou: 0,
                        },
                        qIsAutoFormat: true,
                        id: 'tooltip',
                      },
                    ],
                    qAttrDimInfo: [],
                    qTrendLines: [],
                    cId: 'jBAthEq',
                  },
                  {
                    qFallbackTitle: 'Center line',
                    qApprMaxGlyphCount: 15,
                    qCardinal: 0,
                    qSortIndicator: 'N',
                    qNumFormat: {
                      qType: 'U',
                      qnDec: 0,
                      qUseThou: 0,
                    },
                    qMin: 11596.638655462186,
                    qMax: 13623.511904761905,
                    qIsAutoFormat: true,
                    qAttrExprInfo: [
                      {
                        qMin: 'NaN',
                        qMax: 'NaN',
                        qFallbackTitle: "='Median'",
                        qNumFormat: {
                          qType: 'U',
                          qnDec: 0,
                          qUseThou: 0,
                        },
                        qIsAutoFormat: true,
                        id: 'tooltip',
                      },
                    ],
                    qAttrDimInfo: [],
                    qTrendLines: [],
                    cId: 'pkcaV',
                  },
                  {
                    qFallbackTitle: 'Box end',
                    qApprMaxGlyphCount: 15,
                    qCardinal: 0,
                    qSortIndicator: 'N',
                    qNumFormat: {
                      qType: 'U',
                      qnDec: 0,
                      qUseThou: 0,
                    },
                    qMin: 16467.961165048546,
                    qMax: 17526.041666666668,
                    qIsAutoFormat: true,
                    qAttrExprInfo: [
                      {
                        qMin: 'NaN',
                        qMax: 'NaN',
                        qFallbackTitle: "='Third quartile'",
                        qNumFormat: {
                          qType: 'U',
                          qnDec: 0,
                          qUseThou: 0,
                        },
                        qIsAutoFormat: true,
                        id: 'tooltip',
                      },
                    ],
                    qAttrDimInfo: [],
                    qTrendLines: [],
                    cId: 'DHyBjD',
                  },
                  {
                    qFallbackTitle: 'Last whisker',
                    qApprMaxGlyphCount: 15,
                    qCardinal: 0,
                    qSortIndicator: 'N',
                    qNumFormat: {
                      qType: 'U',
                      qnDec: 0,
                      qUseThou: 0,
                    },
                    qMin: 18304.424778761062,
                    qMax: 21554.878048780487,
                    qIsAutoFormat: true,
                    qAttrExprInfo: [
                      {
                        qMin: 'NaN',
                        qMax: 'NaN',
                        qFallbackTitle: "='95th percentile'",
                        qNumFormat: {
                          qType: 'U',
                          qnDec: 0,
                          qUseThou: 0,
                        },
                        qIsAutoFormat: true,
                        id: 'tooltip',
                      },
                    ],
                    qAttrDimInfo: [],
                    qTrendLines: [],
                    cId: 'HWmcPF',
                  },
                ],
                qEffectiveInterColumnSortOrder: [0, 1, 2, 3, 4, 5],
                qGrandTotalRow: [
                  {
                    qText: '1591,3198823035',
                    qNum: 1591.3198823034888,
                    qElemNumber: -1,
                    qState: 'X',
                    qIsTotalCell: true,
                  },
                  {
                    qText: '5085,1470588235',
                    qNum: 5085.14705882353,
                    qElemNumber: -1,
                    qState: 'X',
                    qIsTotalCell: true,
                  },
                  {
                    qText: '12076,638655462',
                    qNum: 12076.638655462186,
                    qElemNumber: -1,
                    qState: 'X',
                    qIsTotalCell: true,
                  },
                  {
                    qText: '17653,658536585',
                    qNum: 17653.658536585364,
                    qElemNumber: -1,
                    qState: 'X',
                    qIsTotalCell: true,
                  },
                  {
                    qText: '20971,657633243',
                    qNum: 20971.657633242998,
                    qElemNumber: -1,
                    qState: 'X',
                    qIsTotalCell: true,
                  },
                ],
                qDataPages: [
                  {
                    qMatrix: [
                      [
                        {
                          qText: 'X',
                          qNum: 'NaN',
                          qElemNumber: 1,
                          qState: 'O',
                        },
                        {
                          qText: '1901,0256410256',
                          qNum: 1901.025641025641,
                          qElemNumber: 0,
                          qState: 'L',
                          qAttrExps: {
                            qValues: [
                              {
                                qText: 'green',
                                qNum: 'NaN',
                              },
                              {
                                qText: '5th percentile',
                                qNum: 'NaN',
                              },
                            ],
                          },
                        },
                        {
                          qText: '6503,2142857143',
                          qNum: 6503.214285714285,
                          qElemNumber: 0,
                          qState: 'L',
                          qAttrExps: {
                            qValues: [
                              {
                                qText: 'First quartile',
                                qNum: 'NaN',
                              },
                            ],
                          },
                        },
                        {
                          qText: '13623,511904762',
                          qNum: 13623.511904761905,
                          qElemNumber: 0,
                          qState: 'L',
                          qAttrExps: {
                            qValues: [
                              {
                                qText: 'Median',
                                qNum: 'NaN',
                              },
                            ],
                          },
                        },
                        {
                          qText: '17526,041666667',
                          qNum: 17526.041666666668,
                          qElemNumber: 0,
                          qState: 'L',
                          qAttrExps: {
                            qValues: [
                              {
                                qText: 'Third quartile',
                                qNum: 'NaN',
                              },
                            ],
                          },
                        },
                        {
                          qText: '19965,277777778',
                          qNum: 19965.27777777778,
                          qElemNumber: 0,
                          qState: 'L',
                          qAttrExps: {
                            qValues: [
                              {
                                qText: '95th percentile',
                                qNum: 'NaN',
                              },
                            ],
                          },
                        },
                      ],
                      [
                        {
                          qText: 'Z',
                          qNum: 'NaN',
                          qElemNumber: 0,
                          qState: 'O',
                        },
                        {
                          qText: '2482,7586206897',
                          qNum: 2482.7586206896553,
                          qElemNumber: 0,
                          qState: 'L',
                          qAttrExps: {
                            qValues: [
                              {
                                qText: 'green',
                                qNum: 'NaN',
                              },
                              {
                                qText: '5th percentile',
                                qNum: 'NaN',
                              },
                            ],
                          },
                        },
                        {
                          qText: '6115',
                          qNum: 6115,
                          qElemNumber: 0,
                          qState: 'L',
                          qAttrExps: {
                            qValues: [
                              {
                                qText: 'First quartile',
                                qNum: 'NaN',
                              },
                            ],
                          },
                        },
                        {
                          qText: '12615,922330097',
                          qNum: 12615.922330097088,
                          qElemNumber: 0,
                          qState: 'L',
                          qAttrExps: {
                            qValues: [
                              {
                                qText: 'Median',
                                qNum: 'NaN',
                              },
                            ],
                          },
                        },
                        {
                          qText: '16467,961165049',
                          qNum: 16467.961165048546,
                          qElemNumber: 0,
                          qState: 'L',
                          qAttrExps: {
                            qValues: [
                              {
                                qText: 'Third quartile',
                                qNum: 'NaN',
                              },
                            ],
                          },
                        },
                        {
                          qText: '18304,424778761',
                          qNum: 18304.424778761062,
                          qElemNumber: 0,
                          qState: 'L',
                          qAttrExps: {
                            qValues: [
                              {
                                qText: '95th percentile',
                                qNum: 'NaN',
                              },
                            ],
                          },
                        },
                      ],
                      [
                        {
                          qText: 'Y',
                          qNum: 'NaN',
                          qElemNumber: 2,
                          qState: 'O',
                        },
                        {
                          qText: '2596,1306653809',
                          qNum: 2596.1306653809065,
                          qElemNumber: 0,
                          qState: 'L',
                          qAttrExps: {
                            qValues: [
                              {
                                qText: 'green',
                                qNum: 'NaN',
                              },
                              {
                                qText: '5th percentile',
                                qNum: 'NaN',
                              },
                            ],
                          },
                        },
                        {
                          qText: '6415,4411764706',
                          qNum: 6415.441176470588,
                          qElemNumber: 0,
                          qState: 'L',
                          qAttrExps: {
                            qValues: [
                              {
                                qText: 'First quartile',
                                qNum: 'NaN',
                              },
                            ],
                          },
                        },
                        {
                          qText: '11596,638655462',
                          qNum: 11596.638655462186,
                          qElemNumber: 0,
                          qState: 'L',
                          qAttrExps: {
                            qValues: [
                              {
                                qText: 'Median',
                                qNum: 'NaN',
                              },
                            ],
                          },
                        },
                        {
                          qText: '16651,977864316',
                          qNum: 16651.977864316457,
                          qElemNumber: 0,
                          qState: 'L',
                          qAttrExps: {
                            qValues: [
                              {
                                qText: 'Third quartile',
                                qNum: 'NaN',
                              },
                            ],
                          },
                        },
                        {
                          qText: '21554,87804878',
                          qNum: 21554.878048780487,
                          qElemNumber: 0,
                          qState: 'L',
                          qAttrExps: {
                            qValues: [
                              {
                                qText: '95th percentile',
                                qNum: 'NaN',
                              },
                            ],
                          },
                        },
                      ],
                    ],
                    qTails: [],
                    qArea: {
                      qLeft: 0,
                      qTop: 0,
                      qWidth: 6,
                      qHeight: 3,
                    },
                  },
                ],
                qPivotDataPages: [],
                qStackedDataPages: [],
                qMode: 'S',
                qNoOfLeftDims: -1,
                qTreeNodesOnDim: [],
                qColumnOrder: [],
              },
            },
            outliers: {
              qHyperCube: {
                qSize: {
                  qcx: 1,
                  qcy: 6,
                },
                qDimensionInfo: [
                  {
                    qFallbackTitle:
                      '=aggr( If( Avg(Expression2)*10000 < Fractile( total <[Dim3]> Aggr( Avg(Expression2)*10000, [Dim3], [Dim2] ) ,0.05 ) or Avg(Expression2)*10000 > Fractile( total <[Dim3]> Aggr( Avg(Expression2)*10000, [Dim3], [Dim2] ) ,0.95 ) or Alt( Aggr( RowNo(), [Dim3], [Dim2] ), 1 ) = 1, [Dim3] & [Dim2] ), [Dim2], [Dim3] )',
                    qApprMaxGlyphCount: 2,
                    qCardinal: 6,
                    qSortIndicator: 'A',
                    qGroupFallbackTitles: [
                      '=aggr( If( Avg(Expression2)*10000 < Fractile( total <[Dim3]> Aggr( Avg(Expression2)*10000, [Dim3], [Dim2] ) ,0.05 ) or Avg(Expression2)*10000 > Fractile( total <[Dim3]> Aggr( Avg(Expression2)*10000, [Dim3], [Dim2] ) ,0.95 ) or Alt( Aggr( RowNo(), [Dim3], [Dim2] ), 1 ) = 1, [Dim3] & [Dim2] ), [Dim2], [Dim3] )',
                    ],
                    qGroupPos: 0,
                    qStateCounts: {
                      qLocked: 0,
                      qSelected: 0,
                      qOption: 6,
                      qDeselected: 0,
                      qAlternative: 0,
                      qExcluded: 0,
                      qSelectedExcluded: 0,
                      qLockedExcluded: 0,
                    },
                    qTags: ['$ascii', '$text'],
                    qDimensionType: 'D',
                    qGrouping: 'N',
                    qNumFormat: {
                      qType: 'U',
                      qnDec: 0,
                      qUseThou: 0,
                    },
                    qIsAutoFormat: true,
                    qGroupFieldDefs: [
                      '=aggr( If( Avg(Expression2)*10000 < Fractile( total <[Dim3]> Aggr( Avg(Expression2)*10000, [Dim3], [Dim2] ) ,0.05 ) or Avg(Expression2)*10000 > Fractile( total <[Dim3]> Aggr( Avg(Expression2)*10000, [Dim3], [Dim2] ) ,0.95 ) or Alt( Aggr( RowNo(), [Dim3], [Dim2] ), 1 ) = 1, [Dim3] & [Dim2] ), [Dim2], [Dim3] )',
                    ],
                    qMin: 'NaN',
                    qMax: 'NaN',
                    qAttrExprInfo: [],
                    qAttrDimInfo: [],
                    qIsCalculated: true,
                    qCardinalities: {
                      qCardinal: 6,
                      qHypercubeCardinal: 6,
                      qAllValuesCardinal: -1,
                    },
                    autoSort: true,
                    cId: 'AzpS',
                    othersLabel: 'Others',
                  },
                  {
                    qFallbackTitle: 'Dim3',
                    qApprMaxGlyphCount: 1,
                    qCardinal: 3,
                    qSortIndicator: 'A',
                    qGroupFallbackTitles: ['Dim3'],
                    qGroupPos: 0,
                    qStateCounts: {
                      qLocked: 0,
                      qSelected: 0,
                      qOption: 3,
                      qDeselected: 0,
                      qAlternative: 0,
                      qExcluded: 0,
                      qSelectedExcluded: 0,
                      qLockedExcluded: 0,
                    },
                    qTags: ['$ascii', '$text'],
                    qDimensionType: 'D',
                    qGrouping: 'N',
                    qNumFormat: {
                      qType: 'U',
                      qnDec: 0,
                      qUseThou: 0,
                    },
                    qIsAutoFormat: true,
                    qGroupFieldDefs: ['Dim3'],
                    qMin: 'NaN',
                    qMax: 'NaN',
                    qAttrExprInfo: [],
                    qAttrDimInfo: [],
                    qCardinalities: {
                      qCardinal: 3,
                      qHypercubeCardinal: 3,
                      qAllValuesCardinal: -1,
                    },
                    autoSort: true,
                    cId: 'Yjthu',
                    othersLabel: 'Others',
                  },
                  {
                    qFallbackTitle: 'Dim2',
                    qApprMaxGlyphCount: 1,
                    qCardinal: 6,
                    qSortIndicator: 'A',
                    qGroupFallbackTitles: ['Dim2'],
                    qGroupPos: 0,
                    qStateCounts: {
                      qLocked: 0,
                      qSelected: 0,
                      qOption: 6,
                      qDeselected: 0,
                      qAlternative: 0,
                      qExcluded: 0,
                      qSelectedExcluded: 0,
                      qLockedExcluded: 0,
                    },
                    qTags: ['$ascii', '$text'],
                    qDimensionType: 'D',
                    qGrouping: 'N',
                    qNumFormat: {
                      qType: 'U',
                      qnDec: 0,
                      qUseThou: 0,
                    },
                    qIsAutoFormat: true,
                    qGroupFieldDefs: ['Dim2'],
                    qMin: 'NaN',
                    qMax: 'NaN',
                    qAttrExprInfo: [],
                    qAttrDimInfo: [],
                    qCardinalities: {
                      qCardinal: 6,
                      qHypercubeCardinal: 3,
                      qAllValuesCardinal: -1,
                    },
                    autoSort: true,
                    cId: 'eCbjdH',
                    othersLabel: 'Others',
                  },
                ],
                qMeasureInfo: [
                  {
                    qFallbackTitle:
                      '=aggr( If( Avg(Expression2)*10000 < Fractile( total <[Dim3]> Aggr( Avg(Expression2)*10000, [Dim3], [Dim2] ) ,0.05 ) or Avg(Expression2)*10000 > Fractile( total <[Dim3]> Aggr( Avg(Expression2)*10000, [Dim3], [Dim2] ) ,0.95 ), Avg(Expression2)*10000 ), [Dim2], [Dim3] )',
                    qApprMaxGlyphCount: 15,
                    qCardinal: 0,
                    qSortIndicator: 'D',
                    qNumFormat: {
                      qType: 'U',
                      qnDec: 0,
                      qUseThou: 0,
                    },
                    qMin: 854.7008547008547,
                    qMax: 22804.878048780487,
                    qIsAutoFormat: true,
                    qAttrExprInfo: [],
                    qAttrDimInfo: [],
                    qTrendLines: [],
                    autoSort: true,
                    cId: 'PQEMC',
                    numFormatFromTemplate: true,
                  },
                ],
                qEffectiveInterColumnSortOrder: [1, 0, 2],
                qGrandTotalRow: [],
                qDataPages: [],
                qPivotDataPages: [],
                qStackedDataPages: [
                  {
                    qData: [
                      {
                        qElemNo: 0,
                        qValue: 0,
                        qType: 'R',
                        qMaxPos: 66511.94972630695,
                        qMinNeg: 0,
                        qUp: 0,
                        qDown: 0,
                        qRow: 0,
                        qSubNodes: [
                          {
                            qText: 'X',
                            qElemNo: 1,
                            qValue: 'NaN',
                            qType: 'N',
                            qMaxPos: 21502.849002849005,
                            qMinNeg: 0,
                            qUp: 0,
                            qDown: 0,
                            qRow: 0,
                            qSubNodes: [
                              {
                                qText: 'Xf',
                                qElemNo: 3,
                                qValue: 'NaN',
                                qType: 'N',
                                qMaxPos: 20648.14814814815,
                                qMinNeg: 0,
                                qUp: 0,
                                qDown: 0,
                                qRow: 0,
                                qSubNodes: [
                                  {
                                    qText: 'f',
                                    qElemNo: 1,
                                    qValue: 'NaN',
                                    qType: 'N',
                                    qMaxPos: 20648.14814814815,
                                    qMinNeg: 0,
                                    qUp: 0,
                                    qDown: 0,
                                    qRow: 0,
                                    qSubNodes: [
                                      {
                                        qText: '20648,148148148',
                                        qElemNo: 0,
                                        qValue: 20648.14814814815,
                                        qType: 'V',
                                        qMaxPos: 0,
                                        qMinNeg: 0,
                                        qUp: 0,
                                        qDown: 0,
                                        qRow: 0,
                                        qSubNodes: [],
                                      },
                                    ],
                                  },
                                ],
                              },
                              {
                                qText: 'Xa',
                                qElemNo: 2,
                                qValue: 'NaN',
                                qType: 'N',
                                qMaxPos: 854.7008547008547,
                                qMinNeg: 0,
                                qUp: 0,
                                qDown: 0,
                                qRow: 1,
                                qSubNodes: [
                                  {
                                    qText: 'a',
                                    qElemNo: 0,
                                    qValue: 'NaN',
                                    qType: 'N',
                                    qMaxPos: 854.7008547008547,
                                    qMinNeg: 0,
                                    qUp: 0,
                                    qDown: 0,
                                    qRow: 1,
                                    qSubNodes: [
                                      {
                                        qText: '854,70085470085',
                                        qElemNo: 0,
                                        qValue: 854.7008547008547,
                                        qType: 'V',
                                        qMaxPos: 0,
                                        qMinNeg: 0,
                                        qUp: 0,
                                        qDown: 0,
                                        qRow: 1,
                                        qSubNodes: [],
                                      },
                                    ],
                                  },
                                ],
                              },
                            ],
                          },
                          {
                            qText: 'Z',
                            qElemNo: 0,
                            qValue: 'NaN',
                            qType: 'N',
                            qMaxPos: 20482.911199267623,
                            qMinNeg: 0,
                            qUp: 0,
                            qDown: 0,
                            qRow: 2,
                            qSubNodes: [
                              {
                                qText: 'Ze',
                                qElemNo: 1,
                                qValue: 'NaN',
                                qType: 'N',
                                qMaxPos: 18672.566371681416,
                                qMinNeg: 0,
                                qUp: 0,
                                qDown: 0,
                                qRow: 2,
                                qSubNodes: [
                                  {
                                    qText: 'e',
                                    qElemNo: 2,
                                    qValue: 'NaN',
                                    qType: 'N',
                                    qMaxPos: 18672.566371681416,
                                    qMinNeg: 0,
                                    qUp: 0,
                                    qDown: 0,
                                    qRow: 2,
                                    qSubNodes: [
                                      {
                                        qText: '18672,566371681',
                                        qElemNo: 0,
                                        qValue: 18672.566371681416,
                                        qType: 'V',
                                        qMaxPos: 0,
                                        qMinNeg: 0,
                                        qUp: 0,
                                        qDown: 0,
                                        qRow: 2,
                                        qSubNodes: [],
                                      },
                                    ],
                                  },
                                ],
                              },
                              {
                                qText: 'Za',
                                qElemNo: 5,
                                qValue: 'NaN',
                                qType: 'N',
                                qMaxPos: 1810.344827586207,
                                qMinNeg: 0,
                                qUp: 0,
                                qDown: 0,
                                qRow: 3,
                                qSubNodes: [
                                  {
                                    qText: 'a',
                                    qElemNo: 0,
                                    qValue: 'NaN',
                                    qType: 'N',
                                    qMaxPos: 1810.344827586207,
                                    qMinNeg: 0,
                                    qUp: 0,
                                    qDown: 0,
                                    qRow: 3,
                                    qSubNodes: [
                                      {
                                        qText: '1810,3448275862',
                                        qElemNo: 0,
                                        qValue: 1810.344827586207,
                                        qType: 'V',
                                        qMaxPos: 0,
                                        qMinNeg: 0,
                                        qUp: 0,
                                        qDown: 0,
                                        qRow: 3,
                                        qSubNodes: [],
                                      },
                                    ],
                                  },
                                ],
                              },
                            ],
                          },
                          {
                            qText: 'Y',
                            qElemNo: 2,
                            qValue: 'NaN',
                            qType: 'N',
                            qMaxPos: 24526.189524190322,
                            qMinNeg: 0,
                            qUp: 0,
                            qDown: 0,
                            qRow: 4,
                            qSubNodes: [
                              {
                                qText: 'Ya',
                                qElemNo: 4,
                                qValue: 'NaN',
                                qType: 'N',
                                qMaxPos: 1721.311475409836,
                                qMinNeg: 0,
                                qUp: 0,
                                qDown: 0,
                                qRow: 4,
                                qSubNodes: [
                                  {
                                    qText: 'a',
                                    qElemNo: 0,
                                    qValue: 'NaN',
                                    qType: 'N',
                                    qMaxPos: 1721.311475409836,
                                    qMinNeg: 0,
                                    qUp: 0,
                                    qDown: 0,
                                    qRow: 4,
                                    qSubNodes: [
                                      {
                                        qText: '1721,3114754098',
                                        qElemNo: 0,
                                        qValue: 1721.311475409836,
                                        qType: 'V',
                                        qMaxPos: 0,
                                        qMinNeg: 0,
                                        qUp: 0,
                                        qDown: 0,
                                        qRow: 4,
                                        qSubNodes: [],
                                      },
                                    ],
                                  },
                                ],
                              },
                              {
                                qText: 'Yf',
                                qElemNo: 0,
                                qValue: 'NaN',
                                qType: 'N',
                                qMaxPos: 22804.878048780487,
                                qMinNeg: 0,
                                qUp: 0,
                                qDown: 0,
                                qRow: 5,
                                qSubNodes: [
                                  {
                                    qText: 'f',
                                    qElemNo: 1,
                                    qValue: 'NaN',
                                    qType: 'N',
                                    qMaxPos: 22804.878048780487,
                                    qMinNeg: 0,
                                    qUp: 0,
                                    qDown: 0,
                                    qRow: 5,
                                    qSubNodes: [
                                      {
                                        qText: '22804,87804878',
                                        qElemNo: 0,
                                        qValue: 22804.878048780487,
                                        qType: 'V',
                                        qMaxPos: 0,
                                        qMinNeg: 0,
                                        qUp: 0,
                                        qDown: 0,
                                        qRow: 5,
                                        qSubNodes: [],
                                      },
                                    ],
                                  },
                                ],
                              },
                            ],
                          },
                        ],
                      },
                    ],
                    qArea: {
                      qLeft: 0,
                      qTop: 0,
                      qWidth: 1,
                      qHeight: 3,
                    },
                  },
                ],
                qMode: 'K',
                qNoOfLeftDims: 3,
                qTreeNodesOnDim: [],
                qColumnOrder: [],
              },
            },
          },
          snapshotData: {
            object: {
              size: {
                w: 945,
                h: 391,
              },
            },
            rtl: false,
            content: {
              chartData: {},
              size: {},
            },
            parent: {
              h: 857,
              w: 1920,
            },
          },
          visualizationType: 'boxplot',
          sourceObjectId: 'DrMGCv',
          sheetId: '7a3b3d88-153a-4ed6-abbc-36cf58d11047',
          timestamp: 1628151056875,
          isClone: false,
          supportExport: true,
        };
      },
      getEffectiveProperties: {},
    },
  ],
});
