export default () => ({
  instanceConfig: {
    context: {
      theme: 'senseish',
    },
  },
  genericObjects: [
    {
      getLayout() {
        return {
          qInfo: {
            qId: '525b48e3-4a32-40f5-8072-59876589daf3',
            qType: 'embeddedsnapshot',
          },
          qMeta: {
            privileges: ['read', 'update', 'delete', 'publish'],
            title: '',
            description: '',
            annotation: '',
          },
          qBookmark: {
            qStateData: [
              {
                qStateName: '$',
                qFieldItems: [],
              },
              {
                qStateName: 'state 2',
                qFieldItems: [],
              },
            ],
            qUtcModifyTime: 44468.38520833333,
            qVariableItems: [],
            qPatches: [],
          },
          qFieldInfos: [],
          creationDate: '2021-09-29T09:14:42.319Z',
          qSelectionInfo: {
            qInSelections: false,
          },
          boxplotDef: {
            qHyperCube: {
              qSize: {
                qcx: 2,
                qcy: 12,
              },
              qDimensionInfo: [
                {
                  qFallbackTitle: 'Month',
                  qApprMaxGlyphCount: 3,
                  qCardinal: 12,
                  qSortIndicator: 'A',
                  qGroupFallbackTitles: ['Month'],
                  qGroupPos: 0,
                  qStateCounts: {
                    qLocked: 0,
                    qSelected: 0,
                    qOption: 12,
                    qDeselected: 0,
                    qAlternative: 0,
                    qExcluded: 0,
                    qSelectedExcluded: 0,
                    qLockedExcluded: 0,
                  },
                  qTags: ['$numeric', '$integer'],
                  qDimensionType: 'N',
                  qGrouping: 'N',
                  qNumFormat: {
                    qType: 'U',
                    qnDec: 0,
                    qUseThou: 0,
                  },
                  qIsAutoFormat: true,
                  qGroupFieldDefs: ['Month'],
                  qMin: 1,
                  qMax: 12,
                  qContinuousAxes: true,
                  qAttrExprInfo: [],
                  qAttrDimInfo: [],
                  qCardinalities: {
                    qCardinal: 12,
                    qHypercubeCardinal: 12,
                    qAllValuesCardinal: -1,
                  },
                  qLibraryId: '50a5fd45-6023-487a-a6d1-f71681f0dafe',
                  title: 'Month',
                  autoSort: true,
                  cId: 'zhUPHf',
                  othersLabel: 'Others',
                },
              ],
              qMeasureInfo: [
                {
                  qFallbackTitle: 'Actual Amount',
                  qApprMaxGlyphCount: 11,
                  qCardinal: 0,
                  qSortIndicator: 'D',
                  qNumFormat: {
                    qType: 'U',
                    qnDec: 0,
                    qUseThou: 0,
                  },
                  qMin: 44884486.24000001,
                  qMax: 45959669.79999998,
                  qIsAutoFormat: true,
                  qAttrExprInfo: [],
                  qAttrDimInfo: [],
                  qLibraryId: 'uQbd',
                  qTrendLines: [],
                  autoSort: true,
                  cId: 'zNPr',
                  numFormatFromTemplate: true,
                  quarantine: {
                    qNumFormat: {},
                    isCustomFormatted: false,
                  },
                },
              ],
              qEffectiveInterColumnSortOrder: [1, 0],
              qGrandTotalRow: [
                {
                  qText: '46258458.11',
                  qNum: 46258458.110000014,
                  qElemNumber: -1,
                  qState: 'X',
                  qIsTotalCell: true,
                },
              ],
              qDataPages: [],
              qPivotDataPages: [],
              qStackedDataPages: [],
              qMode: 'S',
              qNoOfLeftDims: -1,
              qTreeNodesOnDim: [],
              qColumnOrder: [],
            },
            calculations: {
              auto: true,
              mode: 'tukey',
              parameters: {
                tukey: 1.5,
                fractiles: 0.01,
                stdDev: 3,
              },
            },
            elements: {
              firstWhisker: {
                name: '',
                expression: null,
              },
              boxStart: {
                name: '',
                expression: null,
              },
              boxMiddle: {
                name: '',
                expression: null,
              },
              boxEnd: {
                name: '',
                expression: null,
              },
              lastWhisker: {
                name: '',
                expression: null,
              },
              outliers: {
                include: true,
                sortOutliers: true,
              },
            },
            presentation: {
              whiskers: {
                show: true,
              },
            },
            color: {
              auto: true,
              mode: 'primary',
              box: {
                paletteColor: {
                  color: '#e6e6e6',
                  index: -1,
                },
              },
              point: {
                paletteColor: {
                  color: '#4477aa',
                  index: 6,
                },
              },
              expressionIsColor: true,
              useBaseColors: 'off',
              expressionLabel: '',
            },
            sorting: {
              autoSort: true,
            },
          },
          refLine: {
            refLines: [],
          },
          showTitles: true,
          title: '',
          subtitle: '',
          footnote: '',
          disableNavMenu: false,
          showDetails: false,
          showDisclaimer: true,
          orientation: 'vertical',
          gridlines: {
            auto: true,
            spacing: 2,
          },
          measureAxis: {
            show: 'all',
            dock: 'near',
            spacing: 1,
            autoMinMax: true,
            minMax: 'min',
            min: 0,
            max: 10,
          },
          dimensionAxis: {
            show: 'all',
            label: 'auto',
            dock: 'near',
          },
          visualization: 'boxplot',
          version: '0.26.2',
          sorting: {
            autoSort: true,
            elementId: 'firstWhisker',
            sortCriteria: {
              sortByAscii: 0,
              sortByExpression: 0,
              sortByNumeric: 0,
            },
          },
          qUndoExclude: {
            hashCode: -1600404227,
            box: {
              qHyperCube: {
                qSize: {
                  qcx: 5,
                  qcy: 1,
                },
                qDimensionInfo: [],
                qMeasureInfo: [
                  {
                    qFallbackTitle: 'First whisker',
                    qApprMaxGlyphCount: 11,
                    qCardinal: 0,
                    qSortIndicator: 'N',
                    qNumFormat: {
                      qType: 'R',
                      qnDec: 14,
                      qUseThou: 1,
                      qFmt: '##############',
                      qDec: '.',
                    },
                    qMin: 44884486.24000001,
                    qMax: 44884486.24000001,
                    qIsAutoFormat: true,
                    qAttrExprInfo: [
                      {
                        qMin: 'NaN',
                        qMax: 'NaN',
                        qFallbackTitle: "='Box start - 1.5 IQR'",
                        qNumFormat: {
                          qType: 'U',
                          qnDec: 0,
                          qUseThou: 0,
                        },
                        qIsAutoFormat: true,
                        id: 'tooltip',
                      },
                    ],
                    qAttrDimInfo: [],
                    qTrendLines: [],
                    cId: 'MqNjuP',
                  },
                  {
                    qFallbackTitle: 'Box start',
                    qApprMaxGlyphCount: 10,
                    qCardinal: 0,
                    qSortIndicator: 'N',
                    qNumFormat: {
                      qType: 'U',
                      qnDec: 0,
                      qUseThou: 0,
                    },
                    qMin: 45060894.60000001,
                    qMax: 45060894.60000001,
                    qIsAutoFormat: true,
                    qAttrExprInfo: [
                      {
                        qMin: 'NaN',
                        qMax: 'NaN',
                        qFallbackTitle: "='First quartile'",
                        qNumFormat: {
                          qType: 'U',
                          qnDec: 0,
                          qUseThou: 0,
                        },
                        qIsAutoFormat: true,
                        id: 'tooltip',
                      },
                    ],
                    qAttrDimInfo: [],
                    qTrendLines: [],
                    cId: 'mmNMXzg',
                  },
                  {
                    qFallbackTitle: 'Center line',
                    qApprMaxGlyphCount: 11,
                    qCardinal: 0,
                    qSortIndicator: 'N',
                    qNumFormat: {
                      qType: 'U',
                      qnDec: 0,
                      qUseThou: 0,
                    },
                    qMin: 45125846.19000001,
                    qMax: 45125846.19000001,
                    qIsAutoFormat: true,
                    qAttrExprInfo: [
                      {
                        qMin: 'NaN',
                        qMax: 'NaN',
                        qFallbackTitle: "='Median'",
                        qNumFormat: {
                          qType: 'U',
                          qnDec: 0,
                          qUseThou: 0,
                        },
                        qIsAutoFormat: true,
                        id: 'tooltip',
                      },
                    ],
                    qAttrDimInfo: [],
                    qTrendLines: [],
                    cId: 'BAfanDQ',
                  },
                  {
                    qFallbackTitle: 'Box end',
                    qApprMaxGlyphCount: 13,
                    qCardinal: 0,
                    qSortIndicator: 'N',
                    qNumFormat: {
                      qType: 'U',
                      qnDec: 0,
                      qUseThou: 0,
                    },
                    qMin: 45286156.5475,
                    qMax: 45286156.5475,
                    qIsAutoFormat: true,
                    qAttrExprInfo: [
                      {
                        qMin: 'NaN',
                        qMax: 'NaN',
                        qFallbackTitle: "='Third quartile'",
                        qNumFormat: {
                          qType: 'U',
                          qnDec: 0,
                          qUseThou: 0,
                        },
                        qIsAutoFormat: true,
                        id: 'tooltip',
                      },
                    ],
                    qAttrDimInfo: [],
                    qTrendLines: [],
                    cId: 'kkYpBm',
                  },
                  {
                    qFallbackTitle: 'Last whisker',
                    qApprMaxGlyphCount: 14,
                    qCardinal: 0,
                    qSortIndicator: 'N',
                    qNumFormat: {
                      qType: 'R',
                      qnDec: 14,
                      qUseThou: 1,
                      qFmt: '##############',
                      qDec: '.',
                    },
                    qMin: 45624049.468749985,
                    qMax: 45624049.468749985,
                    qIsAutoFormat: true,
                    qAttrExprInfo: [
                      {
                        qMin: 'NaN',
                        qMax: 'NaN',
                        qFallbackTitle: "='Box end + 1.5 IQR'",
                        qNumFormat: {
                          qType: 'U',
                          qnDec: 0,
                          qUseThou: 0,
                        },
                        qIsAutoFormat: true,
                        id: 'tooltip',
                      },
                    ],
                    qAttrDimInfo: [],
                    qTrendLines: [],
                    cId: 'amrDJ',
                  },
                ],
                qEffectiveInterColumnSortOrder: [0, 1, 2, 3, 4],
                qGrandTotalRow: [
                  {
                    qText: '44884486.24',
                    qNum: 44884486.24000001,
                    qElemNumber: -1,
                    qState: 'X',
                    qIsTotalCell: true,
                  },
                  {
                    qText: '45060894.6',
                    qNum: 45060894.60000001,
                    qElemNumber: -1,
                    qState: 'X',
                    qIsTotalCell: true,
                  },
                  {
                    qText: '45125846.19',
                    qNum: 45125846.19000001,
                    qElemNumber: -1,
                    qState: 'X',
                    qIsTotalCell: true,
                  },
                  {
                    qText: '45286156.5475',
                    qNum: 45286156.5475,
                    qElemNumber: -1,
                    qState: 'X',
                    qIsTotalCell: true,
                  },
                  {
                    qText: '45624049.46875',
                    qNum: 45624049.468749985,
                    qElemNumber: -1,
                    qState: 'X',
                    qIsTotalCell: true,
                  },
                ],
                qDataPages: [
                  {
                    qMatrix: [
                      [
                        {
                          qText: '44884486.24',
                          qNum: 44884486.24000001,
                          qElemNumber: 0,
                          qState: 'L',
                          qAttrExps: {
                            qValues: [
                              {
                                qText: 'Box start - 1.5 IQR',
                                qNum: 'NaN',
                              },
                            ],
                          },
                          qInExtRow: true,
                        },
                        {
                          qText: '45060894.6',
                          qNum: 45060894.60000001,
                          qElemNumber: 0,
                          qState: 'L',
                          qAttrExps: {
                            qValues: [
                              {
                                qText: 'First quartile',
                                qNum: 'NaN',
                              },
                            ],
                          },
                          qInExtRow: true,
                        },
                        {
                          qText: '45125846.19',
                          qNum: 45125846.19000001,
                          qElemNumber: 0,
                          qState: 'L',
                          qAttrExps: {
                            qValues: [
                              {
                                qText: 'Median',
                                qNum: 'NaN',
                              },
                            ],
                          },
                          qInExtRow: true,
                        },
                        {
                          qText: '45286156.5475',
                          qNum: 45286156.5475,
                          qElemNumber: 0,
                          qState: 'L',
                          qAttrExps: {
                            qValues: [
                              {
                                qText: 'Third quartile',
                                qNum: 'NaN',
                              },
                            ],
                          },
                          qInExtRow: true,
                        },
                        {
                          qText: '45624049.46875',
                          qNum: 45624049.468749985,
                          qElemNumber: 0,
                          qState: 'L',
                          qAttrExps: {
                            qValues: [
                              {
                                qText: 'Box end + 1.5 IQR',
                                qNum: 'NaN',
                              },
                            ],
                          },
                          qInExtRow: true,
                        },
                      ],
                    ],
                    qTails: [],
                    qArea: {
                      qLeft: 0,
                      qTop: 0,
                      qWidth: 5,
                      qHeight: 1,
                    },
                  },
                ],
                qPivotDataPages: [],
                qStackedDataPages: [],
                qMode: 'S',
                qNoOfLeftDims: -1,
                qTreeNodesOnDim: [],
                qColumnOrder: [],
              },
            },
            outliers: {
              qHyperCube: {
                qSize: {
                  qcx: 1,
                  qcy: 2,
                },
                qDimensionInfo: [
                  {
                    qFallbackTitle:
                      '=aggr( If( Sum ([Actual Amount]) < Rangemax(Fractile( total  Aggr( Sum ([Actual Amount]),  [Month] ) ,0.25 ) - ((Fractile( total  Aggr( Sum ([Actual Amount]),  [Month] ) ,0.75 ) - Fractile( total  Aggr( Sum ([Actual Amount]),  [Month] ) ,0.25 )) * 1.5), Min( total  Aggr( Sum ([Actual Amount]),  [Month] )  )) or Sum ([Actual Amount]) > Rangemin(Fractile( total  Aggr( Sum ([Actual Amount]),  [Month] ) ,0.75 ) + ((Fractile( total  Aggr( Sum ([Actual Amount]),  [Month] ) ,0.75 ) - Fractile( total  Aggr( Sum ([Actual Amount]),  [Month] ) ,0.25 )) * 1.5), Max( total  Aggr( Sum ([Actual Amount]),  [Month] )  )),  [Month] ), [Month] )',
                    qApprMaxGlyphCount: 3,
                    qCardinal: 2,
                    qSortIndicator: 'A',
                    qGroupFallbackTitles: [
                      '=aggr( If( Sum ([Actual Amount]) < Rangemax(Fractile( total  Aggr( Sum ([Actual Amount]),  [Month] ) ,0.25 ) - ((Fractile( total  Aggr( Sum ([Actual Amount]),  [Month] ) ,0.75 ) - Fractile( total  Aggr( Sum ([Actual Amount]),  [Month] ) ,0.25 )) * 1.5), Min( total  Aggr( Sum ([Actual Amount]),  [Month] )  )) or Sum ([Actual Amount]) > Rangemin(Fractile( total  Aggr( Sum ([Actual Amount]),  [Month] ) ,0.75 ) + ((Fractile( total  Aggr( Sum ([Actual Amount]),  [Month] ) ,0.75 ) - Fractile( total  Aggr( Sum ([Actual Amount]),  [Month] ) ,0.25 )) * 1.5), Max( total  Aggr( Sum ([Actual Amount]),  [Month] )  )),  [Month] ), [Month] )',
                    ],
                    qGroupPos: 0,
                    qStateCounts: {
                      qLocked: 0,
                      qSelected: 0,
                      qOption: 2,
                      qDeselected: 0,
                      qAlternative: 0,
                      qExcluded: 0,
                      qSelectedExcluded: 0,
                      qLockedExcluded: 0,
                    },
                    qTags: ['$numeric', '$integer'],
                    qDimensionType: 'N',
                    qGrouping: 'N',
                    qNumFormat: {
                      qType: 'U',
                      qnDec: 0,
                      qUseThou: 0,
                    },
                    qIsAutoFormat: true,
                    qGroupFieldDefs: [
                      '=aggr( If( Sum ([Actual Amount]) < Rangemax(Fractile( total  Aggr( Sum ([Actual Amount]),  [Month] ) ,0.25 ) - ((Fractile( total  Aggr( Sum ([Actual Amount]),  [Month] ) ,0.75 ) - Fractile( total  Aggr( Sum ([Actual Amount]),  [Month] ) ,0.25 )) * 1.5), Min( total  Aggr( Sum ([Actual Amount]),  [Month] )  )) or Sum ([Actual Amount]) > Rangemin(Fractile( total  Aggr( Sum ([Actual Amount]),  [Month] ) ,0.75 ) + ((Fractile( total  Aggr( Sum ([Actual Amount]),  [Month] ) ,0.75 ) - Fractile( total  Aggr( Sum ([Actual Amount]),  [Month] ) ,0.25 )) * 1.5), Max( total  Aggr( Sum ([Actual Amount]),  [Month] )  )),  [Month] ), [Month] )',
                    ],
                    qMin: 9,
                    qMax: 11,
                    qAttrExprInfo: [],
                    qAttrDimInfo: [],
                    qIsCalculated: true,
                    qCardinalities: {
                      qCardinal: 2,
                      qHypercubeCardinal: 2,
                      qAllValuesCardinal: -1,
                    },
                    autoSort: true,
                    cId: 'zwNBK',
                    othersLabel: 'Others',
                  },
                  {
                    qFallbackTitle: 'Month',
                    qApprMaxGlyphCount: 3,
                    qCardinal: 12,
                    qSortIndicator: 'A',
                    qGroupFallbackTitles: ['Month'],
                    qGroupPos: 0,
                    qStateCounts: {
                      qLocked: 0,
                      qSelected: 0,
                      qOption: 12,
                      qDeselected: 0,
                      qAlternative: 0,
                      qExcluded: 0,
                      qSelectedExcluded: 0,
                      qLockedExcluded: 0,
                    },
                    qTags: ['$numeric', '$integer'],
                    qDimensionType: 'N',
                    qGrouping: 'N',
                    qNumFormat: {
                      qType: 'U',
                      qnDec: 0,
                      qUseThou: 0,
                    },
                    qIsAutoFormat: true,
                    qGroupFieldDefs: ['Month'],
                    qMin: 9,
                    qMax: 11,
                    qContinuousAxes: true,
                    qAttrExprInfo: [],
                    qAttrDimInfo: [],
                    qCardinalities: {
                      qCardinal: 12,
                      qHypercubeCardinal: 2,
                      qAllValuesCardinal: -1,
                    },
                    qLibraryId: '50a5fd45-6023-487a-a6d1-f71681f0dafe',
                    title: 'Month',
                    autoSort: true,
                    cId: 'zhUPHf',
                    othersLabel: 'Others',
                  },
                ],
                qMeasureInfo: [
                  {
                    qFallbackTitle:
                      '=aggr( If( Sum ([Actual Amount]) < Rangemax(Fractile( total  Aggr( Sum ([Actual Amount]),  [Month] ) ,0.25 ) - ((Fractile( total  Aggr( Sum ([Actual Amount]),  [Month] ) ,0.75 ) - Fractile( total  Aggr( Sum ([Actual Amount]),  [Month] ) ,0.25 )) * 1.5), Min( total  Aggr( Sum ([Actual Amount]),  [Month] )  )) or Sum ([Actual Amount]) > Rangemin(Fractile( total  Aggr( Sum ([Actual Amount]),  [Month] ) ,0.75 ) + ((Fractile( total  Aggr( Sum ([Actual Amount]),  [Month] ) ,0.75 ) - Fractile( total  Aggr( Sum ([Actual Amount]),  [Month] ) ,0.25 )) * 1.5), Max( total  Aggr( Sum ([Actual Amount]),  [Month] )  )), Sum ([Actual Amount]) ), [Month] )',
                    qApprMaxGlyphCount: 11,
                    qCardinal: 0,
                    qSortIndicator: 'D',
                    qNumFormat: {
                      qType: 'U',
                      qnDec: 0,
                      qUseThou: 0,
                    },
                    qMin: 45944669.839999996,
                    qMax: 45959669.79999998,
                    qIsAutoFormat: true,
                    qAttrExprInfo: [],
                    qAttrDimInfo: [],
                    qTrendLines: [],
                    autoSort: true,
                    cId: 'zNPr',
                    numFormatFromTemplate: true,
                    quarantine: {
                      qNumFormat: {},
                      isCustomFormatted: false,
                    },
                  },
                ],
                qEffectiveInterColumnSortOrder: [0, 1],
                qGrandTotalRow: [],
                qDataPages: [],
                qPivotDataPages: [],
                qStackedDataPages: [
                  {
                    qData: [
                      {
                        qElemNo: 0,
                        qValue: 0,
                        qType: 'R',
                        qMaxPos: 91904339.63999999,
                        qMinNeg: 0,
                        qUp: 0,
                        qDown: 0,
                        qRow: 0,
                        qSubNodes: [
                          {
                            qText: 'Nov',
                            qElemNo: 1,
                            qValue: 11,
                            qType: 'N',
                            qMaxPos: 45944669.839999996,
                            qMinNeg: 0,
                            qUp: 0,
                            qDown: 0,
                            qRow: 0,
                            qSubNodes: [
                              {
                                qText: 'Nov',
                                qElemNo: 4,
                                qValue: 11,
                                qType: 'N',
                                qMaxPos: 45944669.839999996,
                                qMinNeg: 0,
                                qUp: 0,
                                qDown: 0,
                                qRow: 0,
                                qSubNodes: [
                                  {
                                    qText: '45944669.84',
                                    qElemNo: 0,
                                    qValue: 45944669.839999996,
                                    qType: 'V',
                                    qMaxPos: 0,
                                    qMinNeg: 0,
                                    qUp: 0,
                                    qDown: 0,
                                    qRow: 0,
                                    qSubNodes: [],
                                  },
                                ],
                              },
                            ],
                          },
                          {
                            qText: 'Sep',
                            qElemNo: 0,
                            qValue: 9,
                            qType: 'N',
                            qMaxPos: 45959669.79999998,
                            qMinNeg: 0,
                            qUp: 0,
                            qDown: 0,
                            qRow: 1,
                            qSubNodes: [
                              {
                                qText: 'Sep',
                                qElemNo: 3,
                                qValue: 9,
                                qType: 'N',
                                qMaxPos: 45959669.79999998,
                                qMinNeg: 0,
                                qUp: 0,
                                qDown: 0,
                                qRow: 1,
                                qSubNodes: [
                                  {
                                    qText: '45959669.8',
                                    qElemNo: 0,
                                    qValue: 45959669.79999998,
                                    qType: 'V',
                                    qMaxPos: 0,
                                    qMinNeg: 0,
                                    qUp: 0,
                                    qDown: 0,
                                    qRow: 1,
                                    qSubNodes: [],
                                  },
                                ],
                              },
                            ],
                          },
                        ],
                      },
                    ],
                    qArea: {
                      qLeft: 0,
                      qTop: 0,
                      qWidth: 1,
                      qHeight: 2,
                    },
                  },
                ],
                qMode: 'K',
                qNoOfLeftDims: 2,
                qTreeNodesOnDim: [],
                qColumnOrder: [],
              },
            },
          },
          snapshotData: {
            object: {
              size: {
                w: 945,
                h: 391,
              },
            },
            rtl: false,
            content: {
              chartData: {},
              size: {},
            },
            parent: {
              h: 857,
              w: 1920,
            },
          },
          visualizationType: 'boxplot',
          sourceObjectId: 'pPTkJMG',
          sheetId: 'bb52098c-5bf6-44f3-b475-c3c817e77f19',
          timestamp: 1632906882296,
          isClone: false,
          supportExport: true,
        };
      },
      getEffectiveProperties: {},
    },
  ],
});
