export default () => ({
  instanceConfig: {
    context: {
      theme: 'senseish',
    },
  },
  genericObjects: [
    {
      getLayout() {
        return {
          qInfo: {
            qId: 'jKMtcZS',
            qType: 'waterfallchart',
          },
          qMeta: {
            privileges: ['read', 'update', 'delete'],
          },
          qSelectionInfo: {},
          qHyperCube: {
            qSize: {
              qcx: 6,
              qcy: 1,
            },
            qDimensionInfo: [],
            qMeasureInfo: [
              {
                qFallbackTitle: 'Central Revenue',
                qApprMaxGlyphCount: 16,
                qCardinal: 0,
                qSortIndicator: 'D',
                qNumFormat: {
                  qType: 'M',
                  qnDec: 2,
                  qUseThou: 0,
                  qFmt: '$#,##0.00;($#,##0.00)',
                  qDec: '.',
                  qThou: ',',
                },
                qMin: -46811256.609999895,
                qMax: -46811256.609999895,
                qAttrExprInfo: [],
                qAttrDimInfo: [],
                qTrendLines: [],
                autoSort: true,
                cId: 'zLpqJq',
                numFormatFromTemplate: true,
                valueType: 'NORMAL',
                subtotal: {
                  enable: false,
                  label: 'Subtotals',
                },
              },
              {
                qFallbackTitle: 'Northeast Revenue',
                qApprMaxGlyphCount: 15,
                qCardinal: 0,
                qSortIndicator: 'D',
                qNumFormat: {
                  qType: 'M',
                  qnDec: 2,
                  qUseThou: 0,
                  qFmt: '$#,##0.00;($#,##0.00)',
                  qDec: '.',
                  qThou: ',',
                },
                qMin: -7225219.810000021,
                qMax: -7225219.810000021,
                qAttrExprInfo: [],
                qAttrDimInfo: [],
                qTrendLines: [],
                autoSort: true,
                cId: 'hPPCTw',
                numFormatFromTemplate: true,
                valueType: 'NORMAL',
                subtotal: {
                  enable: false,
                  label: 'Subtotals',
                },
              },
              {
                qFallbackTitle: 'Southern Revenue',
                qApprMaxGlyphCount: 16,
                qCardinal: 0,
                qSortIndicator: 'D',
                qNumFormat: {
                  qType: 'M',
                  qnDec: 2,
                  qUseThou: 0,
                  qFmt: '$#,##0.00;($#,##0.00)',
                  qDec: '.',
                  qThou: ',',
                },
                qMin: -20746968.910000093,
                qMax: -20746968.910000093,
                qAttrExprInfo: [],
                qAttrDimInfo: [],
                qTrendLines: [],
                autoSort: true,
                cId: 'TnFYY',
                numFormatFromTemplate: true,
                valueType: 'NORMAL',
                subtotal: {
                  enable: false,
                  label: 'Subtotals',
                },
              },
              {
                qFallbackTitle: 'Western Revenue',
                qApprMaxGlyphCount: 16,
                qCardinal: 0,
                qSortIndicator: 'D',
                qNumFormat: {
                  qType: 'M',
                  qnDec: 2,
                  qUseThou: 0,
                  qFmt: '$#,##0.00;($#,##0.00)',
                  qDec: '.',
                  qThou: ',',
                },
                qMin: -23889221.849999767,
                qMax: -23889221.849999767,
                qAttrExprInfo: [],
                qAttrDimInfo: [],
                qTrendLines: [],
                autoSort: true,
                cId: 'sTEacX',
                numFormatFromTemplate: true,
                valueType: 'NORMAL',
                subtotal: {
                  enable: false,
                  label: 'Subtotals',
                },
              },
              {
                qFallbackTitle: 'Revenue',
                qApprMaxGlyphCount: 16,
                qCardinal: 0,
                qSortIndicator: 'D',
                qNumFormat: {
                  qType: 'M',
                  qnDec: 2,
                  qUseThou: 0,
                  qFmt: '$#,##0.00;($#,##0.00)',
                  qDec: '.',
                  qThou: ',',
                },
                qMin: -98672667.18000308,
                qMax: -98672667.18000308,
                qAttrExprInfo: [],
                qAttrDimInfo: [],
                qTrendLines: [],
                autoSort: true,
                cId: 'nnsc',
                numFormatFromTemplate: true,
                valueType: 'SUBTOTAL',
                subtotal: {
                  enable: false,
                  label: 'Subtotals',
                },
              },
              {
                qFallbackTitle: 'Actual Amount',
                qApprMaxGlyphCount: 16,
                qCardinal: 0,
                qSortIndicator: 'D',
                qNumFormat: {
                  qType: 'M',
                  qnDec: 2,
                  qUseThou: 0,
                  qFmt: '$#,##0.00;($#,##0.00)',
                  qDec: '.',
                  qThou: ',',
                },
                qMin: -46258458.10999999,
                qMax: -46258458.10999999,
                qAttrExprInfo: [],
                qAttrDimInfo: [],
                qTrendLines: [],
                autoSort: true,
                cId: 'XpWq',
                numFormatFromTemplate: true,
                valueType: 'INVERSE',
                subtotal: {
                  enable: true,
                  label: 'Subtotals',
                },
              },
            ],
            qEffectiveInterColumnSortOrder: [0, 1, 2, 3, 4, 5],
            qGrandTotalRow: [
              {
                qText: '($46,811,256.61)',
                qNum: -46811256.609999895,
                qElemNumber: -1,
                qState: 'X',
                qIsTotalCell: true,
              },
              {
                qText: '($7,225,219.81)',
                qNum: -7225219.810000021,
                qElemNumber: -1,
                qState: 'X',
                qIsTotalCell: true,
              },
              {
                qText: '($20,746,968.91)',
                qNum: -20746968.910000093,
                qElemNumber: -1,
                qState: 'X',
                qIsTotalCell: true,
              },
              {
                qText: '($23,889,221.85)',
                qNum: -23889221.849999767,
                qElemNumber: -1,
                qState: 'X',
                qIsTotalCell: true,
              },
              {
                qText: '($98,672,667.18)',
                qNum: -98672667.18000308,
                qElemNumber: -1,
                qState: 'X',
                qIsTotalCell: true,
              },
              {
                qText: '($46,258,458.11)',
                qNum: -46258458.10999999,
                qElemNumber: -1,
                qState: 'X',
                qIsTotalCell: true,
              },
            ],
            qDataPages: [
              {
                qMatrix: [
                  [
                    {
                      qText: '($46,811,256.61)',
                      qNum: -46811256.609999895,
                      qElemNumber: 0,
                      qState: 'L',
                      qInExtRow: true,
                    },
                    {
                      qText: '($7,225,219.81)',
                      qNum: -7225219.810000021,
                      qElemNumber: 0,
                      qState: 'L',
                      qInExtRow: true,
                    },
                    {
                      qText: '($20,746,968.91)',
                      qNum: -20746968.910000093,
                      qElemNumber: 0,
                      qState: 'L',
                      qInExtRow: true,
                    },
                    {
                      qText: '($23,889,221.85)',
                      qNum: -23889221.849999767,
                      qElemNumber: 0,
                      qState: 'L',
                      qInExtRow: true,
                    },
                    {
                      qText: '($98,672,667.18)',
                      qNum: -98672667.18000308,
                      qElemNumber: 0,
                      qState: 'L',
                      qInExtRow: true,
                    },
                    {
                      qText: '($46,258,458.11)',
                      qNum: -46258458.10999999,
                      qElemNumber: 0,
                      qState: 'L',
                      qInExtRow: true,
                    },
                  ],
                ],
                qTails: [],
                qArea: {
                  qLeft: 0,
                  qTop: 0,
                  qWidth: 6,
                  qHeight: 1,
                },
              },
            ],
            qPivotDataPages: [],
            qStackedDataPages: [],
            qMode: 'S',
            qNoOfLeftDims: -1,
            qTreeNodesOnDim: [],
            qColumnOrder: [],
          },
          qDef: {
            numFormatFromTemplate: true,
            qNumFormat: {
              qType: 'M',
              qnDec: 2,
              qDec: '.',
              qThou: ',',
              qFmt: '$#,##0.00;($#,##0.00)',
            },
            isCustomFormatted: false,
          },
          refLine: {
            refLines: [],
          },
          showTitles: true,
          title: '',
          subtitle: '',
          footnote: '',
          disableNavMenu: false,
          showDetails: false,
          gridlines: {
            auto: true,
            spacing: 2,
          },
          dataPoint: {
            showLabels: true,
          },
          color: {
            auto: false,
            positiveValue: {
              paletteColor: {
                index: 7,
                color: '#8e477d',
              },
            },
            negativeValue: {
              paletteColor: {
                index: 10,
                color: '#f93f17',
              },
            },
            subtotal: {
              paletteColor: {
                index: 14,
                color: '#545352',
              },
            },
          },
          legend: {
            show: true,
            dock: 'bottom',
          },
          measureAxis: {
            show: 'labels',
            dock: 'near',
            spacing: 1,
            autoMinMax: true,
            minMax: 'minMax',
            min: 0,
            max: 10,
          },
          dimensionAxis: {
            show: 'labels',
            label: 'layered',
            dock: 'near',
          },
          visualization: 'waterfallchart',
          version: '0.25.6',
        };
      },
      getEffectiveProperties: {},
    },
  ],
});
