export default () => ({
  instanceConfig: {
    context: {
      theme: 'senseish',
    },
  },
  genericObjects: [
    {
      getLayout() {
        return {
          qInfo: {
            qId: 'adVmab',
            qType: 'waterfallchart',
          },
          qMeta: {
            privileges: ['read', 'update', 'delete'],
          },
          qSelectionInfo: {},
          qHyperCube: {
            qSize: {
              qcx: 6,
              qcy: 1,
            },
            qDimensionInfo: [],
            qMeasureInfo: [
              {
                qFallbackTitle: 'Central Revenue',
                qApprMaxGlyphCount: 11,
                qCardinal: 0,
                qSortIndicator: 'D',
                qNumFormat: {
                  qType: 'R',
                  qnDec: 0,
                  qUseThou: 0,
                  qFmt: '##############',
                  qDec: '.',
                  qThou: ',',
                },
                qMin: 46811256.609999895,
                qMax: 46811256.609999895,
                qIsAutoFormat: true,
                qAttrExprInfo: [],
                qAttrDimInfo: [],
                qLibraryId: 'EmXwes',
                qTrendLines: [],
                autoSort: true,
                cId: 'zLpqJq',
                numFormatFromTemplate: true,
                valueType: 'NORMAL',
                subtotal: {
                  enable: false,
                  label: 'Subtotals',
                },
                quarantine: {
                  qNumFormat: {},
                  isCustomFormatted: false,
                },
              },
              {
                qFallbackTitle: 'Northeast Revenue',
                qApprMaxGlyphCount: 10,
                qCardinal: 0,
                qSortIndicator: 'D',
                qNumFormat: {
                  qType: 'R',
                  qnDec: 0,
                  qUseThou: 0,
                  qFmt: '##############',
                  qDec: '.',
                  qThou: ',',
                },
                qMin: 7225219.810000021,
                qMax: 7225219.810000021,
                qIsAutoFormat: true,
                qAttrExprInfo: [],
                qAttrDimInfo: [],
                qLibraryId: 'Hzya',
                qTrendLines: [],
                autoSort: true,
                cId: 'hPPCTw',
                numFormatFromTemplate: true,
                valueType: 'NORMAL',
                subtotal: {
                  enable: false,
                  label: 'Subtotals',
                },
                quarantine: {
                  qNumFormat: {},
                  isCustomFormatted: false,
                },
              },
              {
                qFallbackTitle: 'Southern Revenue',
                qApprMaxGlyphCount: 11,
                qCardinal: 0,
                qSortIndicator: 'D',
                qNumFormat: {
                  qType: 'R',
                  qnDec: 0,
                  qUseThou: 0,
                  qFmt: '##############',
                  qDec: '.',
                  qThou: ',',
                },
                qMin: 20746968.910000093,
                qMax: 20746968.910000093,
                qIsAutoFormat: true,
                qAttrExprInfo: [],
                qAttrDimInfo: [],
                qLibraryId: 'VSvJmYg',
                qTrendLines: [],
                autoSort: true,
                cId: 'TnFYY',
                numFormatFromTemplate: true,
                valueType: 'NORMAL',
                subtotal: {
                  enable: false,
                  label: 'Subtotals',
                },
                quarantine: {
                  qNumFormat: {},
                  isCustomFormatted: false,
                },
              },
              {
                qFallbackTitle: 'Western Revenue',
                qApprMaxGlyphCount: 11,
                qCardinal: 0,
                qSortIndicator: 'D',
                qNumFormat: {
                  qType: 'R',
                  qnDec: 0,
                  qUseThou: 0,
                  qFmt: '##############',
                  qDec: '.',
                  qThou: ',',
                },
                qMin: 23889221.849999763,
                qMax: 23889221.849999763,
                qIsAutoFormat: true,
                qAttrExprInfo: [],
                qAttrDimInfo: [],
                qLibraryId: 'CtApmJr',
                qTrendLines: [],
                autoSort: true,
                cId: 'sTEacX',
                numFormatFromTemplate: true,
                valueType: 'NORMAL',
                subtotal: {
                  enable: false,
                  label: 'Subtotals',
                },
                quarantine: {
                  qNumFormat: {},
                  isCustomFormatted: false,
                },
              },
              {
                qFallbackTitle: 'Revenue',
                qApprMaxGlyphCount: 15,
                qCardinal: 0,
                qSortIndicator: 'D',
                qNumFormat: {
                  qType: 'R',
                  qnDec: 0,
                  qUseThou: 0,
                  qFmt: '##############',
                  qDec: '.',
                  qThou: ',',
                },
                qMin: 98672667.18000308,
                qMax: 98672667.18000308,
                qIsAutoFormat: true,
                qAttrExprInfo: [],
                qAttrDimInfo: [],
                qLibraryId: 'Wwmauk',
                qTrendLines: [],
                autoSort: true,
                cId: 'nnsc',
                numFormatFromTemplate: true,
                valueType: 'SUBTOTAL',
                subtotal: {
                  enable: false,
                  label: 'Subtotals',
                },
                quarantine: {
                  qNumFormat: {},
                  isCustomFormatted: false,
                },
              },
              {
                qFallbackTitle: 'Actual Amount',
                qApprMaxGlyphCount: 11,
                qCardinal: 0,
                qSortIndicator: 'D',
                qNumFormat: {
                  qType: 'U',
                  qnDec: 0,
                  qUseThou: 0,
                },
                qMin: 46258458.10999999,
                qMax: 46258458.10999999,
                qIsAutoFormat: true,
                qAttrExprInfo: [],
                qAttrDimInfo: [],
                qLibraryId: 'uQbd',
                qTrendLines: [],
                autoSort: true,
                cId: 'XpWq',
                numFormatFromTemplate: true,
                valueType: 'INVERSE',
                subtotal: {
                  enable: true,
                  label: 'Subtotals',
                },
                quarantine: {
                  qNumFormat: {},
                  isCustomFormatted: false,
                },
              },
            ],
            qEffectiveInterColumnSortOrder: [0, 1, 2, 3, 4, 5],
            qGrandTotalRow: [
              {
                qText: '46811256.61',
                qNum: 46811256.609999895,
                qElemNumber: -1,
                qState: 'X',
                qIsTotalCell: true,
              },
              {
                qText: '7225219.81',
                qNum: 7225219.810000021,
                qElemNumber: -1,
                qState: 'X',
                qIsTotalCell: true,
              },
              {
                qText: '20746968.91',
                qNum: 20746968.910000093,
                qElemNumber: -1,
                qState: 'X',
                qIsTotalCell: true,
              },
              {
                qText: '23889221.85',
                qNum: 23889221.849999763,
                qElemNumber: -1,
                qState: 'X',
                qIsTotalCell: true,
              },
              {
                qText: '98672667.180003',
                qNum: 98672667.18000308,
                qElemNumber: -1,
                qState: 'X',
                qIsTotalCell: true,
              },
              {
                qText: '46258458.11',
                qNum: 46258458.10999999,
                qElemNumber: -1,
                qState: 'X',
                qIsTotalCell: true,
              },
            ],
            qDataPages: [
              {
                qMatrix: [
                  [
                    {
                      qText: '46811256.61',
                      qNum: 46811256.609999895,
                      qElemNumber: 0,
                      qState: 'L',
                      qInExtRow: true,
                    },
                    {
                      qText: '7225219.81',
                      qNum: 7225219.810000021,
                      qElemNumber: 0,
                      qState: 'L',
                      qInExtRow: true,
                    },
                    {
                      qText: '20746968.91',
                      qNum: 20746968.910000093,
                      qElemNumber: 0,
                      qState: 'L',
                      qInExtRow: true,
                    },
                    {
                      qText: '23889221.85',
                      qNum: 23889221.849999763,
                      qElemNumber: 0,
                      qState: 'L',
                      qInExtRow: true,
                    },
                    {
                      qText: '98672667.180003',
                      qNum: 98672667.18000308,
                      qElemNumber: 0,
                      qState: 'L',
                      qInExtRow: true,
                    },
                    {
                      qText: '46258458.11',
                      qNum: 46258458.10999999,
                      qElemNumber: 0,
                      qState: 'L',
                      qInExtRow: true,
                    },
                  ],
                ],
                qTails: [],
                qArea: {
                  qLeft: 0,
                  qTop: 0,
                  qWidth: 6,
                  qHeight: 1,
                },
              },
            ],
            qPivotDataPages: [],
            qStackedDataPages: [],
            qMode: 'S',
            qNoOfLeftDims: -1,
            qTreeNodesOnDim: [],
            qColumnOrder: [],
          },
          qDef: {
            numFormatFromTemplate: true,
            qNumFormat: {},
            isCustomFormatted: false,
          },
          refLine: {
            refLines: [],
          },
          showTitles: true,
          title: '',
          subtitle: '',
          footnote: '',
          disableNavMenu: false,
          showDetails: false,
          gridlines: {
            auto: true,
            spacing: 2,
          },
          dataPoint: {
            showLabels: true,
          },
          color: {
            auto: true,
            positiveValue: {
              paletteColor: {
                index: 6,
                color: null,
              },
            },
            negativeValue: {
              paletteColor: {
                index: -1,
                color: '#cc6677',
              },
            },
            subtotal: {
              paletteColor: {
                index: -1,
                color: '#c3c3c3',
              },
            },
          },
          legend: {
            show: true,
            dock: 'auto',
          },
          measureAxis: {
            show: 'labels',
            dock: 'near',
            spacing: 1,
            autoMinMax: false,
            minMax: 'minMax',
            min: -1234,
            max: 100000000,
          },
          dimensionAxis: {
            show: 'labels',
            label: 'auto',
            dock: 'near',
          },
          visualization: 'waterfallchart',
          version: '0.25.6',
        };
      },
      getEffectiveProperties: {},
    },
  ],
});
