export default () => ({
  instanceConfig: {
    context: {
      theme: 'senseish',
    },
  },
  snConfig: {
    options: {
      renderer: 'svg',
    },
  },
  genericObjects: [
    {
      getLayout() {
        return {
          qInfo: {
            qId: '6bd3545e-23d4-4311-8e28-4f3db9206e55',
            qType: 'embeddedsnapshot',
          },
          qMeta: {
            privileges: ['read', 'update', 'delete', 'exportdata'],
          },
          qBookmark: {
            qStateData: [
              {
                qStateName: '$',
                qFieldItems: [],
              },
            ],
            qUtcModifyTime: 44413.626967592594,
            qVariableItems: [],
            qPatches: [],
          },
          qFieldInfos: [],
          creationDate: '2021-08-05T13:02:50.241Z',
          qSelectionInfo: {},
          refLine: {
            refLines: [],
          },
          showTitles: true,
          title: '',
          subtitle: '',
          footnote: '',
          disableNavMenu: false,
          showDetails: false,
          showDisclaimer: true,
          orientation: 'vertical',
          gridlines: {
            auto: true,
            spacing: 2,
          },
          measureAxis: {
            show: 'all',
            dock: 'near',
            spacing: 1,
            autoMinMax: true,
            minMax: 'min',
            min: 0,
            max: 10,
          },
          dimensionAxis: {
            show: 'all',
            label: 'auto',
            dock: 'near',
          },
          visualization: 'distributionplot',
          qHyperCube: {
            qSize: {
              qcx: 1,
              qcy: 8,
            },
            qDimensionInfo: [
              {
                qFallbackTitle: 'Dim2',
                qApprMaxGlyphCount: 1,
                qCardinal: 6,
                qSortIndicator: 'A',
                qGroupFallbackTitles: ['Dim2'],
                qGroupPos: 0,
                qStateCounts: {
                  qLocked: 0,
                  qSelected: 0,
                  qOption: 6,
                  qDeselected: 0,
                  qAlternative: 0,
                  qExcluded: 0,
                  qSelectedExcluded: 0,
                  qLockedExcluded: 0,
                },
                qTags: ['$ascii', '$text'],
                qDimensionType: 'D',
                qGrouping: 'N',
                qNumFormat: {
                  qType: 'U',
                  qnDec: 0,
                  qUseThou: 0,
                },
                qIsAutoFormat: true,
                qGroupFieldDefs: ['Dim2'],
                qMin: 'NaN',
                qMax: 'NaN',
                qAttrExprInfo: [],
                qAttrDimInfo: [],
                qCardinalities: {
                  qCardinal: 6,
                  qHypercubeCardinal: 4,
                  qAllValuesCardinal: -1,
                },
                autoSort: true,
                cId: 'eCbjdH',
                othersLabel: 'OthersXX',
              },
              {
                qFallbackTitle: 'Dim3',
                qApprMaxGlyphCount: 1,
                qCardinal: 3,
                qSortIndicator: 'A',
                qGroupFallbackTitles: ['Dim3'],
                qGroupPos: 0,
                qStateCounts: {
                  qLocked: 0,
                  qSelected: 0,
                  qOption: 3,
                  qDeselected: 0,
                  qAlternative: 0,
                  qExcluded: 0,
                  qSelectedExcluded: 0,
                  qLockedExcluded: 0,
                },
                qTags: ['$ascii', '$text'],
                qDimensionType: 'D',
                qGrouping: 'N',
                qNumFormat: {
                  qType: 'U',
                  qnDec: 0,
                  qUseThou: 0,
                },
                qIsAutoFormat: true,
                qGroupFieldDefs: ['Dim3'],
                qMin: 'NaN',
                qMax: 'NaN',
                qAttrExprInfo: [],
                qAttrDimInfo: [],
                qCardinalities: {
                  qCardinal: 3,
                  qHypercubeCardinal: 2,
                  qAllValuesCardinal: -1,
                },
                autoSort: true,
                cId: 'Yjthu',
                othersLabel: 'Others',
              },
            ],
            qMeasureInfo: [
              {
                qFallbackTitle: 'Avg(Expression2)',
                qApprMaxGlyphCount: 6,
                qCardinal: 0,
                qSortIndicator: 'D',
                qNumFormat: {
                  qType: 'F',
                  qnDec: 4,
                  qUseThou: 1,
                  qFmt: '# ##0,0000',
                  qDec: ',',
                  qThou: ' ',
                },
                qMin: 0.08547008547008547,
                qMax: 1.8364197530864197,
                qIsAutoFormat: true,
                qAttrExprInfo: [],
                qAttrDimInfo: [],
                qTrendLines: [],
                autoSort: true,
                cId: 'PQEMC',
                numFormatFromTemplate: true,
              },
            ],
            qEffectiveInterColumnSortOrder: [1, 0],
            qGrandTotalRow: [],
            qDataPages: [],
            qPivotDataPages: [],
            qStackedDataPages: [
              {
                qData: [],
                qArea: {
                  qLeft: 0,
                  qTop: 0,
                  qWidth: 0,
                  qHeight: 0,
                },
              },
            ],
            qMode: 'K',
            qNoOfLeftDims: 2,
            qHasOtherValues: true,
            qTreeNodesOnDim: [],
            qColumnOrder: [],
          },
          presentation: {
            visibleComponents: 'points_box',
          },
          dataPoint: {
            bubbleScales: 100,
            displacement: 'none',
          },
          color: {
            point: {
              auto: false,
              mode: 'byDimension',
              useBaseColors: 'off',
              paletteColor: {
                index: 6,
                color: '#4477aa',
              },
              useDimColVal: true,
              persistent: true,
              expressionIsColor: true,
              measureScheme: 'sg',
              reverseScheme: false,
              dimensionScheme: '12',
              autoMinMax: true,
              measureMin: 0,
              measureMax: 10,
              expressionLabel: '',
              altLabel: 'Dim2',
              byDimDef: {
                label: 'Dim2',
                key: 'Dim2',
                type: 'expression',
                activeDimensionIndex: 0,
              },
              expression: 4278222848,
            },
            formatting: {
              numFormatFromTemplate: true,
            },
            box: {
              paletteColor: {
                index: -1,
                color: '#e6e6e6',
              },
            },
          },
          legend: {
            show: true,
            dock: 'auto',
            showTitle: true,
          },
          sorting: {
            autoSort: true,
          },
          qUndoExclude: {
            hashCode: 1466910606,
            qHyperCube: {
              qSize: {
                qcx: 1,
                qcy: 8,
              },
              qDimensionInfo: [
                {
                  qFallbackTitle: 'Dim2',
                  qApprMaxGlyphCount: 1,
                  qCardinal: 6,
                  qSortIndicator: 'A',
                  qGroupFallbackTitles: ['Dim2'],
                  qGroupPos: 0,
                  qStateCounts: {
                    qLocked: 0,
                    qSelected: 0,
                    qOption: 6,
                    qDeselected: 0,
                    qAlternative: 0,
                    qExcluded: 0,
                    qSelectedExcluded: 0,
                    qLockedExcluded: 0,
                  },
                  qTags: ['$ascii', '$text'],
                  qDimensionType: 'D',
                  qGrouping: 'N',
                  qNumFormat: {
                    qType: 'U',
                    qnDec: 0,
                    qUseThou: 0,
                  },
                  qIsAutoFormat: true,
                  qGroupFieldDefs: ['Dim2'],
                  qMin: 'NaN',
                  qMax: 'NaN',
                  qAttrExprInfo: [],
                  qAttrDimInfo: [
                    {
                      qCardinal: 6,
                      qSize: {
                        qcx: 2,
                        qcy: 3,
                      },
                      qFallbackTitle: 'Dim2',
                      id: 'colorByAlternative',
                      label: 'Dim2',
                    },
                  ],
                  qCardinalities: {
                    qCardinal: 6,
                    qHypercubeCardinal: 4,
                    qAllValuesCardinal: -1,
                  },
                  autoSort: true,
                  cId: 'eCbjdH',
                  othersLabel: 'OthersXX',
                },
                {
                  qFallbackTitle: 'Dim3',
                  qApprMaxGlyphCount: 1,
                  qCardinal: 3,
                  qSortIndicator: 'A',
                  qGroupFallbackTitles: ['Dim3'],
                  qGroupPos: 0,
                  qStateCounts: {
                    qLocked: 0,
                    qSelected: 0,
                    qOption: 3,
                    qDeselected: 0,
                    qAlternative: 0,
                    qExcluded: 0,
                    qSelectedExcluded: 0,
                    qLockedExcluded: 0,
                  },
                  qTags: ['$ascii', '$text'],
                  qDimensionType: 'D',
                  qGrouping: 'N',
                  qNumFormat: {
                    qType: 'U',
                    qnDec: 0,
                    qUseThou: 0,
                  },
                  qIsAutoFormat: true,
                  qGroupFieldDefs: ['Dim3'],
                  qMin: 'NaN',
                  qMax: 'NaN',
                  qAttrExprInfo: [
                    {
                      qMin: 0.08547008547008547,
                      qMax: 0.1721311475409836,
                      qFallbackTitle: 'Min( total <[Dim3]> Aggr( Avg(Expression2), [Dim3], [Dim2] ), 0 )',
                      qMinText: '0,085470085470085',
                      qMaxText: '0,17213114754098',
                      qNumFormat: {
                        qType: 'U',
                        qnDec: 0,
                        qUseThou: 0,
                      },
                      qIsAutoFormat: true,
                      id: 'minBoxValue',
                    },
                    {
                      qMin: 2.064814814814815,
                      qMax: 2.2804878048780486,
                      qFallbackTitle: 'Max( total <[Dim3]> Aggr( Avg(Expression2), [Dim3], [Dim2] ), 1 )',
                      qMinText: '2,0648148148148',
                      qMaxText: '2,280487804878',
                      qNumFormat: {
                        qType: 'U',
                        qnDec: 0,
                        qUseThou: 0,
                      },
                      qIsAutoFormat: true,
                      id: 'maxBoxValue',
                    },
                  ],
                  qAttrDimInfo: [],
                  qCardinalities: {
                    qCardinal: 3,
                    qHypercubeCardinal: 2,
                    qAllValuesCardinal: -1,
                  },
                  autoSort: true,
                  cId: 'Yjthu',
                  othersLabel: 'Others',
                },
              ],
              qMeasureInfo: [
                {
                  qFallbackTitle: 'Avg(Expression2)',
                  qApprMaxGlyphCount: 6,
                  qCardinal: 0,
                  qSortIndicator: 'D',
                  qNumFormat: {
                    qType: 'F',
                    qnDec: 4,
                    qUseThou: 1,
                    qFmt: '# ##0,0000',
                    qDec: ',',
                    qThou: ' ',
                  },
                  qMin: 0.08547008547008547,
                  qMax: 1.8364197530864197,
                  qIsAutoFormat: true,
                  qAttrExprInfo: [],
                  qAttrDimInfo: [],
                  qTrendLines: [],
                  autoSort: true,
                  cId: 'PQEMC',
                  numFormatFromTemplate: true,
                },
              ],
              qEffectiveInterColumnSortOrder: [1, 0],
              qGrandTotalRow: [],
              qDataPages: [],
              qPivotDataPages: [],
              qStackedDataPages: [
                {
                  qData: [
                    {
                      qElemNo: 0,
                      qValue: 0,
                      qType: 'R',
                      qMaxPos: 6.93581711538829,
                      qMinNeg: 0,
                      qUp: 0,
                      qDown: 0,
                      qRow: 0,
                      qSubNodes: [
                        {
                          qText: 'X',
                          qElemNo: 1,
                          qValue: 'NaN',
                          qType: 'N',
                          qMaxPos: 3.5151755528422193,
                          qMinNeg: 0,
                          qUp: 0,
                          qDown: 0,
                          qRow: 0,
                          qSubNodes: [
                            {
                              qText: 'a',
                              qElemNo: 0,
                              qValue: 'NaN',
                              qType: 'N',
                              qMaxPos: 0.08547008547008547,
                              qMinNeg: 0,
                              qUp: 0,
                              qDown: 0,
                              qRow: 0,
                              qSubNodes: [
                                {
                                  qText: '0,0855',
                                  qElemNo: 0,
                                  qValue: 0.08547008547008547,
                                  qType: 'V',
                                  qMaxPos: 0,
                                  qMinNeg: 0,
                                  qUp: 0,
                                  qDown: 0,
                                  qRow: 0,
                                  qSubNodes: [],
                                },
                              ],
                              qAttrDims: {
                                qValues: [
                                  {
                                    qText: 'a',
                                    qElemNo: 0,
                                  },
                                ],
                              },
                            },
                            {
                              qText: 'b',
                              qElemNo: 4,
                              qValue: 'NaN',
                              qType: 'N',
                              qMaxPos: 0.504,
                              qMinNeg: 0,
                              qUp: 0,
                              qDown: 0,
                              qRow: 1,
                              qSubNodes: [
                                {
                                  qText: '0,5040',
                                  qElemNo: 0,
                                  qValue: 0.504,
                                  qType: 'V',
                                  qMaxPos: 0,
                                  qMinNeg: 0,
                                  qUp: 0,
                                  qDown: 0,
                                  qRow: 1,
                                  qSubNodes: [],
                                },
                              ],
                              qAttrDims: {
                                qValues: [
                                  {
                                    qText: 'b',
                                    qElemNo: 4,
                                  },
                                ],
                              },
                            },
                            {
                              qText: 'c',
                              qElemNo: 3,
                              qValue: 'NaN',
                              qType: 'N',
                              qMaxPos: 1.0892857142857142,
                              qMinNeg: 0,
                              qUp: 0,
                              qDown: 0,
                              qRow: 2,
                              qSubNodes: [
                                {
                                  qText: '1,0893',
                                  qElemNo: 0,
                                  qValue: 1.0892857142857142,
                                  qType: 'V',
                                  qMaxPos: 0,
                                  qMinNeg: 0,
                                  qUp: 0,
                                  qDown: 0,
                                  qRow: 2,
                                  qSubNodes: [],
                                },
                              ],
                              qAttrDims: {
                                qValues: [
                                  {
                                    qText: 'c',
                                    qElemNo: 3,
                                  },
                                ],
                              },
                            },
                            {
                              qText: 'OthersXX',
                              qElemNo: -3,
                              qValue: 'NaN',
                              qType: 'O',
                              qMaxPos: 1.8364197530864197,
                              qMinNeg: 0,
                              qUp: 0,
                              qDown: 0,
                              qRow: 3,
                              qSubNodes: [
                                {
                                  qText: '1,8364',
                                  qElemNo: 0,
                                  qValue: 1.8364197530864197,
                                  qType: 'V',
                                  qMaxPos: 0,
                                  qMinNeg: 0,
                                  qUp: 0,
                                  qDown: 0,
                                  qRow: 3,
                                  qSubNodes: [],
                                },
                              ],
                              qAttrDims: {
                                qValues: [
                                  {
                                    qElemNo: -2,
                                  },
                                ],
                              },
                            },
                          ],
                          qAttrExps: {
                            qValues: [
                              {
                                qText: '0,085470085470085',
                                qNum: 0.08547008547008547,
                              },
                              {
                                qText: '2,0648148148148',
                                qNum: 2.064814814814815,
                              },
                            ],
                          },
                        },
                        {
                          qText: 'Others',
                          qElemNo: -3,
                          qValue: 'NaN',
                          qType: 'O',
                          qMaxPos: 3.420641562546071,
                          qMinNeg: 0,
                          qUp: 0,
                          qDown: 0,
                          qRow: 4,
                          qSubNodes: [
                            {
                              qText: 'a',
                              qElemNo: 0,
                              qValue: 'NaN',
                              qType: 'N',
                              qMaxPos: 0.17647058823529413,
                              qMinNeg: 0,
                              qUp: 0,
                              qDown: 0,
                              qRow: 4,
                              qSubNodes: [
                                {
                                  qText: '0,1765',
                                  qElemNo: 0,
                                  qValue: 0.17647058823529413,
                                  qType: 'V',
                                  qMaxPos: 0,
                                  qMinNeg: 0,
                                  qUp: 0,
                                  qDown: 0,
                                  qRow: 4,
                                  qSubNodes: [],
                                },
                              ],
                              qAttrDims: {
                                qValues: [
                                  {
                                    qText: 'a',
                                    qElemNo: 0,
                                  },
                                ],
                              },
                            },
                            {
                              qText: 'b',
                              qElemNo: 4,
                              qValue: 'NaN',
                              qType: 'N',
                              qMaxPos: 0.48828125,
                              qMinNeg: 0,
                              qUp: 0,
                              qDown: 0,
                              qRow: 5,
                              qSubNodes: [
                                {
                                  qText: '0,4883',
                                  qElemNo: 0,
                                  qValue: 0.48828125,
                                  qType: 'V',
                                  qMaxPos: 0,
                                  qMinNeg: 0,
                                  qUp: 0,
                                  qDown: 0,
                                  qRow: 5,
                                  qSubNodes: [],
                                },
                              ],
                              qAttrDims: {
                                qValues: [
                                  {
                                    qText: 'b',
                                    qElemNo: 4,
                                  },
                                ],
                              },
                            },
                            {
                              qText: 'c',
                              qElemNo: 3,
                              qValue: 'NaN',
                              qType: 'N',
                              qMaxPos: 1.0476190476190477,
                              qMinNeg: 0,
                              qUp: 0,
                              qDown: 0,
                              qRow: 6,
                              qSubNodes: [
                                {
                                  qText: '1,0476',
                                  qElemNo: 0,
                                  qValue: 1.0476190476190477,
                                  qType: 'V',
                                  qMaxPos: 0,
                                  qMinNeg: 0,
                                  qUp: 0,
                                  qDown: 0,
                                  qRow: 6,
                                  qSubNodes: [],
                                },
                              ],
                              qAttrDims: {
                                qValues: [
                                  {
                                    qText: 'c',
                                    qElemNo: 3,
                                  },
                                ],
                              },
                            },
                            {
                              qText: 'OthersXX',
                              qElemNo: -3,
                              qValue: 'NaN',
                              qType: 'O',
                              qMaxPos: 1.7082706766917293,
                              qMinNeg: 0,
                              qUp: 0,
                              qDown: 0,
                              qRow: 7,
                              qSubNodes: [
                                {
                                  qText: '1,7083',
                                  qElemNo: 0,
                                  qValue: 1.7082706766917293,
                                  qType: 'V',
                                  qMaxPos: 0,
                                  qMinNeg: 0,
                                  qUp: 0,
                                  qDown: 0,
                                  qRow: 7,
                                  qSubNodes: [],
                                },
                              ],
                              qAttrDims: {
                                qValues: [
                                  {
                                    qElemNo: -2,
                                  },
                                ],
                              },
                            },
                          ],
                          qAttrExps: {
                            qValues: [
                              {
                                qText: '0,17213114754098',
                                qNum: 0.1721311475409836,
                              },
                              {
                                qText: '2,280487804878',
                                qNum: 2.2804878048780486,
                              },
                            ],
                          },
                        },
                      ],
                    },
                  ],
                  qArea: {
                    qLeft: 0,
                    qTop: 0,
                    qWidth: 1,
                    qHeight: 2,
                  },
                },
              ],
              qMode: 'K',
              qNoOfLeftDims: 2,
              qHasOtherValues: true,
              qTreeNodesOnDim: [],
              qColumnOrder: [],
            },
            legendData: null,
          },
          snapshotData: {
            object: {
              size: {
                w: 945,
                h: 391,
              },
            },
            rtl: false,
            content: {
              chartData: {},
              size: {},
            },
            parent: {
              h: 857,
              w: 1920,
            },
          },
          visualizationType: 'distributionplot',
          sourceObjectId: 'xnKEa',
          sheetId: '7a3b3d88-153a-4ed6-abbc-36cf58d11047',
          timestamp: 1628168570217,
          isClone: false,
          supportExport: true,
        };
      },
      getEffectiveProperties: {},
    },
  ],
});
